Add embedded subtitles support
movie-web/movie-web pull request #1007
Opened 2024-03-12 23:08 UTC by ssssobek

This pull request resolves #906

 - [x] I have read and agreed to the [code of conduct](https://github.com/movie-web/movie-web/blob/dev/.github/CODE_OF_CONDUCT.md).
 - [x] I have read and complied with the [contributing guidelines](https://github.com/movie-web/movie-web/blob/dev/.github/CONTRIBUTING.md).
 - [x] What I'm implementing was assigned to me and is an [approved issue](https://github.com/movie-web/movie-web/issues?q=is%3Aopen+is%3Aissue+label%3Aapproved). For reference, please take a look at our [GitHub projects](https://github.com/movie-web/movie-web/projects).
 - [ ] I have tested all of my changes. - I've tested it on almost every episode from #906, but I reckon it needs testing in other cases (I couldn't find any)

# Issues
- Loading the subtitles can be quite slow, probably because there is like 300 vtt files to fetch.
- Subtitle language isn't persistent when switching to source with embedded subtitles (probably because those load faster than hls)

# Notes
- There probably are a few debug prints, will be removed when it's certain that this thing works.

# Preview (on media from #906)
https://github.com/movie-web/movie-web/assets/95639019/eae27deb-ac84-49d3-b06f-6ccf549f58b4

2024-03-12 23:17 UTC, binaryoverload commented
This seems to work well, thanks for your work! One of us will review the code properly soon :D

2024-03-13 20:50 UTC, JorrinKievit commented
Heya, I just did a quick test too. It seems to error out on all languages except for the one that is initially loaded (for me that was Chinese).

2024-03-13 20:55 UTC, JorrinKievit commented
Aha, loaded into another browser for the first time, and I can reproduce it again

2024-03-13 21:05 UTC, JorrinKievit commented
Wow, nevermind. In the end I tracked it down to hls?.setSubtitleOption not existing as a method even though I reinstalled hls with the new version. After removing vite cache everything works 🎉

2024-03-13 21:53 UTC, ssssobek commented
Glad it turned out fine, lol

2024-03-13 22:14 UTC, JorrinKievit requested changes
I think its fine to remove the console.logs. Everything seems to work well!

2024-03-13 22:14 UTC, JorrinKievit commented on src/components/player/hooks/useCaptions.ts
> +              const parsed = subsrt.parse(vtt);
You could use return parseSubtitles(vtt) from /player/utils/captions.ts here

2024-03-13 22:14 UTC, JorrinKievit commented on src/components/player/hooks/useCaptions.ts
> +        const filtered = vttCaptions.reduce(
Could we extract this logic to a filterDuplicateCaptionCues function in captions.ts file too? Makes this code a bit easier to follow

2024-03-13 22:15 UTC, JorrinKievit requested changes

2024-03-13 22:15 UTC, JorrinKievit commented on src/components/player/hooks/useCaptions.ts
> +        setCaption({
These 3 methods are called in both conditions. Let's make a local copy of this object:

```
const captionToSet: Caption = {
        id: caption.id,
        language: caption.language,
        url: caption.url,
        srtData: "",
};
```
Set the srtData in both conditions, and call setCaption, resetSubtitleSpecificSettings and setLanguage at the end

2024-03-14 18:41 UTC, JorrinKievit requested changes

2024-03-14 18:41 UTC, JorrinKievit commented on src/components/player/hooks/useCaptions.ts
> +const filterDuplicateCaptionCues = (cues: ContentCaption[]) =>
Could you move this to /player/utils/captions.ts instead? This file is for react hooks, and that file is more for utility functions for captions

2024-03-14 19:05 UTC, JorrinKievit commented
After the last fix, it's ready to be merged! ❤️

2024-03-14 20:21 UTC, JorrinKievit approved these changes

2024-03-14 20:21 UTC, merged