Better scrape error text for extension
movie-web/movie-web pull request #1042
Opened 2024-03-26 23:41 UTC by sussy-code

This pull request resolves #XXX

 - [x] I have read and agreed to the [code of conduct](https://github.com/movie-web/movie-web/blob/dev/.github/CODE_OF_CONDUCT.md).
 - [x] I have read and complied with the [contributing guidelines](https://github.com/movie-web/movie-web/blob/dev/.github/CONTRIBUTING.md).
 - [x] What I'm implementing was assigned to me and is an [approved issue](https://github.com/movie-web/movie-web/issues?q=is%3Aopen+is%3Aissue+label%3Aapproved). For reference, please take a look at our [GitHub projects](https://github.com/movie-web/movie-web/projects).
 - [x] I have tested all of my changes.

lmk if something is silly i will fix!

2024-03-26 23:46 UTC, binaryoverload requested changes

2024-03-26 23:46 UTC, binaryoverload commented on src/pages/parts/player/ScrapeErrorPart.tsx
> +
This shouldn't be copied, we should move the code into a util. It already exists below

https://github.com/movie-web/movie-web/blob/27e73a8ad47e6d2d21a12021995f6472d4f6a726/src/pages/onboarding/OnboardingExtension.tsx#L26-L42

2024-03-26 23:46 UTC, binaryoverload commented on src/pages/parts/player/ScrapeErrorPart.tsx
> +      }
Instead of setting the Icon and Title, we should check the `extensionState` variable and early return with a specific component if it's in a disabled state

It will make it much cleaner as you won't have to account for all the "If this then that" logic in the main error component

2024-03-26 23:47 UTC, sussy-code commented on src/pages/parts/player/ScrapeErrorPart.tsx
> +      }
ic

2024-03-27 08:50 UTC, binaryoverload requested changes

2024-03-27 08:50 UTC, binaryoverload commented on src/pages/parts/player/ScrapeErrorPart.tsx
> +          <Title>{title}</Title>
```suggestion
          <IconPill icon={Icons.LOCK}>{t("player.scraping.notFound.badge")}</IconPill>
          <Title>t("player.scraping.extensionFailure.disabledTitle")</Title>
```

2024-03-27 08:50 UTC, binaryoverload commented on src/pages/parts/player/ScrapeErrorPart.tsx
> +      }
```suggestion
```

2024-03-27 08:50 UTC, binaryoverload commented on src/pages/parts/player/ScrapeErrorPart.tsx
> +              {t("player.scraping.notFound.homeButton")}
I know it's duplicated, but this should be `player.scraping.extensionFailure.homeButton`

2024-03-27 08:50 UTC, binaryoverload commented on src/pages/parts/player/ScrapeErrorPart.tsx
> +        ) : null}
We don't need the error modal for the extension screen

```suggestion
```

2024-03-28 00:55 UTC, binaryoverload requested changes

2024-03-28 00:55 UTC, binaryoverload commented on src/pages/parts/player/ScrapeErrorPart.tsx
> +            {t("player.scraping.notFound.badge")}
```suggestion
            {t("player.scraping.extensionFailure.badge")}
```

2024-03-28 00:55 UTC, binaryoverload commented on src/assets/locales/en.json
> +        "title": "Extension Disabled"
```suggestion
        "badge": "Extension disabled",
        "homeButton": "Go home",
        "enableExtension": "Enable extension",
        "title": "Please enable the extension",
        "text": "You've installed the movie-web extension. To start using it, you need to enable the extension for this site."
```

2024-03-28 00:55 UTC, binaryoverload commented on src/pages/parts/player/ScrapeErrorPart.tsx
> +          <Title>{t("player.scraping.extensionFailure.disabledTitle")}</Title>
```suggestion
          <Title>{t("player.scraping.extensionFailure.title")}</Title>
```

2024-03-28 00:55 UTC, binaryoverload commented on public/config.js
> +  VITE_BACKEND_URL: "backend.sudo-flix.lol",
Bruh stop commiting your config lmao

2024-03-28 01:11 UTC, sussy-code commented on public/config.js
> +  VITE_BACKEND_URL: "backend.sudo-flix.lol",
STOP I AM SORRY

2024-03-28 01:13 UTC, binaryoverload reviewed
Looks good, just need to test it for myself tomorrow then will merge

2024-03-28 09:17 UTC, merged