Filter unreleased shows/movies.
movie-web/movie-web pull request #1044
Opened 2024-03-27 12:58 UTC by Honkertonken

This pull request resolves #357 

 - [x] I have read and agreed to the [code of conduct](https://github.com/movie-web/movie-web/blob/dev/.github/CODE_OF_CONDUCT.md).
 - [x] I have read and complied with the [contributing guidelines](https://github.com/movie-web/movie-web/blob/dev/.github/CONTRIBUTING.md).
 - [ ] What I'm implementing was assigned to me and is an [approved issue](https://github.com/movie-web/movie-web/issues?q=is%3Aopen+is%3Aissue+label%3Aapproved). For reference, please take a look at our [GitHub projects](https://github.com/movie-web/movie-web/projects).
 - [x] I have tested all of my changes.

![image](https://github.com/movie-web/movie-web/assets/94032937/401ff3d4-5258-4fba-b381-363c7c2a95f8)
![image](https://github.com/movie-web/movie-web/assets/94032937/7734bca3-3979-4dd3-963a-17d13b9140cc)

2024-03-27 13:33 UTC, binaryoverload requested changes
Thanks for the PR. Unfortunately, this doesn't quite line up with our intentions

We want to make it so that unreleased shows are still shown, just not clickable. This will mean that there's no confusion about the movie/show not existing.

If you want to do #900 at the same time that would be perfect for this, but is not a blocker for this PR.

To show that something is unreleased, I think we should add opacity to the card and have the label of "Unreleased" where the year would normally be

2024-03-27 17:53 UTC, Honkertonken commented
Made the necessary changes 

Preview - 

![img](https://github.com/movie-web/movie-web/assets/94032937/3ccb9621-5e51-419e-b444-1b9436872e07)

2024-03-27 19:42 UTC, binaryoverload requested changes
Thanks for making the requested changes - just a couple of comments and then this is good to go!

2024-03-27 19:42 UTC, binaryoverload commented on src/components/media/MediaCard.tsx
> +    dotListContent.push(t("Unreleased"));
Please make this an actual language string - we use paths for the key instead of the original lang text

`media.unreleased` would be good

2024-03-27 19:42 UTC, binaryoverload commented on src/components/media/MediaCard.tsx
> +  if (media.year) {
Instead of checking only if the year is present, we should also check if it is greater than the current year. 

i.e. if a media has a year of 2025, that should also not be linkable and should have "Unreleased" added to the dot list

2024-03-27 19:42 UTC, binaryoverload commented on src/components/media/MediaCard.tsx
> +  if (!props.linkable || !props.media.year) return <span>{content}</span>;
Please alter the year check as described before to check for years in the future

2024-03-28 07:59 UTC, Honkertonken commented
Should be good to go 

Preview 
![img1](https://github.com/movie-web/movie-web/assets/94032937/634c53a4-4c2b-44d7-bd56-be7908117a85)
![img2](https://github.com/movie-web/movie-web/assets/94032937/73fa46bb-7511-4f5d-b047-831f230338e0)

2024-03-28 08:47 UTC, binaryoverload requested changes
Looking good!

Could we have it so that an unreleased media that has a year shows it?

"Movie . 2020 . Unreleased" _should_ fit

2024-03-28 09:13 UTC, JorrinKievit requested changes

2024-03-28 09:13 UTC, JorrinKievit commented on src/components/media/MediaCard.tsx
> +    linkable && !closable && media.year && media.year < currentYear;
I dont think this works, because this would show only movies/shows from the year 2023 and earlier 😁

2024-03-28 11:20 UTC, Honkertonken commented
Done
Preview 
![im1](https://github.com/movie-web/movie-web/assets/94032937/33b4728b-3b90-439e-bf29-a6abc6a23057)
![im2](https://github.com/movie-web/movie-web/assets/94032937/c47fc9d0-94be-4b92-8a43-9b9ba52db7e1)
![im3](https://github.com/movie-web/movie-web/assets/94032937/00113048-470b-4aa2-bc01-bcfaa67eac61)

2024-03-28 11:28 UTC, binaryoverload approved these changes
Looks good, thanks for being patient with the changes!

@JorrinKievit could you have a 2nd glance before I merge? Thanks :)

2024-03-28 11:48 UTC, merged

2024-03-28 17:23 UTC, jacquesvfd commented
Are we sure we don't want unreleased movies to be clickable? Occasionally movies are available before their release date, so it might be better to let the user try anyway. Plus, I imagine having different release dates in different regions creates more potential to break otherwise working movies. 
It might be better to grey them out but leave them clickable, and perhaps add a warning dialogue to tell the user that it's unlikely to be available because it's not released yet.

2024-03-28 17:42 UTC, zisra commented
>  Occasionally movies are available before their release date, so it might be better to let the user try anyway
I second this.

2024-03-28 17:44 UTC, JipFr commented
The same issue was raised for the episode selector without any evidence whatsoever. When are movies and episodes ever available before their release date?

The only situation in which I can imagine this happening is the release date being the date on which it comes to streaming, DVD, or Blu-Ray, but that doesn't seem like a particularly big concern.

2024-03-28 17:49 UTC, jacquesvfd commented
> When are movies and episodes ever available before their release date?

I watched one of the Trolls sequels a few days before release several years ago. It happens. I like having it marked to tell users it's not out yet, but there it doesn't hurt to let the user _try_ if they want to.

2024-03-28 17:59 UTC, blikje7up commented
@JipFr It has happened a few times, like with game of thrones (actually happend multiple times).
If someone has idea's for a clean implementation on how to notify the user but also let them click through it would be nice but definitely not necessary.

2024-03-28 18:15 UTC, JipFr commented
I feel, and this is just me, that this is an issue so incredibly rare that it's not worth adding to the site. If somebody _knows_ something has been leaked and they want to see it, let them torrent it. They're not our average user.

2024-04-02 03:17 UTC, TheScreechingBagel commented
another reason to have them still be clickable: now people aren’t able to open the unreleased piece of media to bookmark

2024-04-02 05:05 UTC, JorrinKievit commented
Which is why this exist https://github.com/movie-web/movie-web/issues/900