feat: add autoplay preference for extension users
movie-web/movie-web pull request #1072
Opened 2024-03-31 19:03 UTC by qtchaos

This pull request resolves #650. 

I'd like opinions on the following:

1. Should self-hosters be able to set an environment variable to enable the autoplay preference for all users?
2. Should users with a custom proxy set be able to use the autoplay option?

Still need to do:

- Fix the lodash mess and properly debounce/throttle or whatever the next episode.

 - [X] I have read and agreed to the [code of conduct](https://github.com/movie-web/movie-web/blob/dev/.github/CODE_OF_CONDUCT.md).
 - [X] I have read and complied with the [contributing guidelines](https://github.com/movie-web/movie-web/blob/dev/.github/CONTRIBUTING.md).
 - [X] What I'm implementing was assigned to me and is an [approved issue](https://github.com/movie-web/movie-web/issues?q=is%3Aopen+is%3Aissue+label%3Aapproved). For reference, please take a look at our [GitHub projects](https://github.com/movie-web/movie-web/projects).
 - [X] I have tested all of my changes.

2024-04-11 19:51 UTC, JorrinKievit requested changes

2024-04-11 19:51 UTC, JorrinKievit commented on src/pages/parts/settings/PreferencesPart.tsx
> +function useIsExtensionActive() {
Why can't you use `isExtensionActiveCached()`?

2024-04-11 19:51 UTC, JorrinKievit commented on src/components/player/atoms/NextEpisodeButton.tsx
> +        conf().ALLOW_AUTOPLAY ||
Can we extract this to a function in some util file with a descriptive name? I saw this used somewhere else

2024-04-11 19:51 UTC, JorrinKievit commented on src/components/player/atoms/NextEpisodeButton.tsx
> +    const interval = setInterval(() => {
Could you explain why we need an interval here, and not just wait for the show to end?

2024-04-11 19:51 UTC, JorrinKievit commented on src/components/player/atoms/NextEpisodeButton.tsx
> +          useAuthStore.getState().proxySet,
I think it should be `(ALLOW_AUTOPLAY && proxySet) || isExtensionActiveChached()` right?

2024-04-11 19:51 UTC, JorrinKievit commented on src/pages/parts/settings/PreferencesPart.tsx
> +          className="bg-dropdown-background hover:bg-dropdown-hoverBackground select-none my-4 cursor-pointer space-x-3 flex items-center max-w-[25rem] py-3 px-4 rounded-lg"
Think you can use the classNames function here to apply the conditional styles below

2024-04-11 20:01 UTC, qtchaos commented on src/components/player/atoms/NextEpisodeButton.tsx
> +          useAuthStore.getState().proxySet,
1. If autoplay is enabled by the host, then you can use the default proxy. 
2. if a custom proxy is set, then you can use
3. if the extension is set, you can use it.

2024-04-11 20:02 UTC, JorrinKievit commented on src/components/player/atoms/NextEpisodeButton.tsx
> +          useAuthStore.getState().proxySet,
Aaah true nevermind, makes sense

2024-04-11 20:07 UTC, qtchaos commented on src/components/player/atoms/NextEpisodeButton.tsx
> +    const interval = setInterval(() => {
If the show ends without an interval, it skips to the very last episode of the season.

2024-04-11 20:09 UTC, JorrinKievit commented on src/components/player/atoms/NextEpisodeButton.tsx
> +    const interval = setInterval(() => {
I'm not sure I understand, why does it skip to the last episode?

2024-04-11 20:49 UTC, qtchaos commented on src/components/player/atoms/NextEpisodeButton.tsx
> +    const interval = setInterval(() => {
I think its a dependency loop (if thats even a thing). Once the `loadNextEpisode` function gets called it updates and so due it being a dependency it creates a loop?

2024-04-12 16:28 UTC, JorrinKievit approved these changes
Works great!

2024-04-12 16:28 UTC, JorrinKievit commented
Let's not forget to update the docs with the new env variable

2024-04-14 20:44 UTC, merged