Fixed next episode button not loading new season
movie-web/movie-web pull request #1098
Opened 2024-04-08 14:04 UTC by dro-1

This pull request resolves #1049.
The next episode button was not showing when the last episode of a season was reached. It is now showing and loads said episode when clicked.

 - [x] I have read and agreed to the [code of conduct](https://github.com/movie-web/movie-web/blob/dev/.github/CODE_OF_CONDUCT.md).
 - [x] I have read and complied with the [contributing guidelines](https://github.com/movie-web/movie-web/blob/dev/.github/CONTRIBUTING.md).
 - [x] What I'm implementing was assigned to me and is an [approved issue](https://github.com/movie-web/movie-web/issues?q=is%3Aopen+is%3Aissue+label%3Aapproved). For reference, please take a look at our [GitHub projects](https://github.com/movie-web/movie-web/projects).
 - [x] I have tested all of my changes.

2024-04-10 16:39 UTC, JorrinKievit requested changes

2024-04-10 16:39 UTC, JorrinKievit commented on src/components/player/atoms/NextEpisodeButton.tsx
> +  const [nextSeason, setNextSeason] = useState<MWSeasonMeta>();
I dont think we need this state. a simple local variable 
 ```
const nextSeason = seasons?.find(
    (season) => season.number === (meta?.season?.number ?? 0) + 1,
  );
```

would suffice

2024-04-10 16:39 UTC, JorrinKievit commented on src/components/player/atoms/NextEpisodeButton.tsx
> +  const [_, seasons] = useSeasonData(
This does not seem necessary if the current episode is not the last episode. Can we make sure this is only called when that is the case? This way we can prevent an unneeded call

2024-04-10 16:39 UTC, JorrinKievit commented on src/components/player/atoms/NextEpisodeButton.tsx
> +  useEffect(() => {
We could use the useAsync hook here. Then we can also get rid of the `nextSeasonEpisodes` local state. We also do not need all the episodes, so only returning the first one from the useAsync hook would suffice.

2024-04-10 16:39 UTC, JorrinKievit commented on src/components/player/atoms/NextEpisodeButton.tsx
> +  useEffect(() => {
We can remove this when we use the local nextSeason variable

2024-04-10 17:06 UTC, JorrinKievit submitted a review, later dismissed
Also the button should show "Next season" when its on the last episode, and there is a next season

2024-04-12 10:46 UTC, dro-1 commented
Made the requested changes @JorrinKievit . 
Awaiting review.

2024-04-12 15:58 UTC, qtchaos requested changes

2024-04-12 15:58 UTC, qtchaos commented on src/components/player/atoms/NextEpisodeButton.tsx
> +          {}
stray braces?

2024-04-12 18:13 UTC, binaryoverload requested changes

2024-04-12 18:13 UTC, binaryoverload commented on src/components/player/atoms/NextEpisodeButton.tsx
> +      if (nextSeasonEpisodes.length) return nextSeasonEpisodes[0];
I generally dislike falsy checks, they are pretty unclear when scanning code

```suggestion
      if (nextSeasonEpisodes.length > 0) return nextSeasonEpisodes[0];
```

2024-04-13 08:19 UTC, dro-1 commented on src/components/player/atoms/NextEpisodeButton.tsx
> +          {}
oh yeah, they definitely are. I'll fix them right away.
do you think it might be reasonable to add that rule to the linter so we catch it next time?

2024-04-13 08:23 UTC, qtchaos commented on src/components/player/atoms/NextEpisodeButton.tsx
> +          {}
If there's a rule for that then I wouldn't be against it

2024-04-14 19:33 UTC, dro-1 commented
Fixed the issues and squashed the commits into one.
I didn't find any linter rule for empty braces so I left that.

2024-04-14 20:07 UTC, binaryoverload commented
@dro-1 FYI, generally, it's bad practice to rebase while your PR is open for review, as it makes it harder for reviewers to see what you've done 

I'll test the PR then LGTM

2024-04-14 20:14 UTC, binaryoverload approved these changes

2024-04-14 20:18 UTC, merged

2024-04-14 20:44 UTC, dro-1 commented
sorry about that @binaryoverload , I'll avoid it in future PRs.
what does LGTM mean 👀

2024-04-14 20:46 UTC, qtchaos commented
> what does LGTM mean 👀

Looking good to me