Added alternate tmdb endpoint to fallback when main url is blocked
movie-web/movie-web pull request #1108
Opened 2024-04-12 06:07 UTC by meghrathod

This pull request resolves #1107 

 - [x] I have read and agreed to the [code of conduct](https://github.com/movie-web/movie-web/blob/dev/.github/CODE_OF_CONDUCT.md).
 - [x] I have read and complied with the [contributing guidelines](https://github.com/movie-web/movie-web/blob/dev/.github/CONTRIBUTING.md).
 - [x] What I'm implementing was assigned to me and is an [approved issue](https://github.com/movie-web/movie-web/issues?q=is%3Aopen+is%3Aissue+label%3Aapproved). For reference, please take a look at our [GitHub projects](https://github.com/movie-web/movie-web/projects).
 - [x] I have tested all of my changes.

2024-04-12 16:57 UTC, JorrinKievit requested changes
I have some thoughts on this one. Because for people where tmdb is blocked, this would mean that every request to tmdb will take 3+ seconds. Even though after the first try we pretty much know that the requests in the future will also fail. 

Maybe we can have an approach similarly to how we implemented `isExtensionActiveCached` ?

1. Do a request, if it fails but the second one works set a boolean that it should use the fallback one.
2. For all tmdb requests after, use the fallback URL.

I think its worth exploring different implementations here, because the current UX could be better

2024-04-12 16:57 UTC, JorrinKievit commented on src/backend/metadata/tmdb.ts
> +      ? setTimeout(() => controller.abort(), 15000)
Why do we need to work with timeouts, and not just use ` { signal: AbortSignal.timeout(5000)` ?

2024-04-12 17:47 UTC, meghrathod commented on src/backend/metadata/tmdb.ts
> +      ? setTimeout(() => controller.abort(), 15000)
Sure, we can do this. Didn't look at this.

2024-04-12 17:52 UTC, meghrathod commented
This is what will happen in my current implementation from the second request onwards all request are served by the new URL as it will become the base URL. I still feel an environment variable must also be present if both the URLs are blocked. Happy know your thoughts.

2024-04-12 18:02 UTC, meghrathod commented on src/backend/metadata/tmdb.ts
> +      ? setTimeout(() => controller.abort(), 15000)
Made this change, pls review. Excuse me as I'm starting out in opensource dev so might make some mistakes.

2024-04-12 18:08 UTC, JorrinKievit requested changes

2024-04-12 18:08 UTC, JorrinKievit commented on src/backend/metadata/tmdb.ts
> +let baseURL = "https://api.themoviedb.org/3";
In my opinion this would be more readable and understandable if we keep track with a shouldUseFallback boolean, and use one of the URLs based on that.

2024-04-12 18:11 UTC, binaryoverload requested changes

2024-04-12 18:11 UTC, binaryoverload commented on src/backend/metadata/tmdb.ts
> +    if (baseURL !== otherUrl) {
Why are we doing checking if the `baseURL` equals the `otherUrl`? This condition will always be false as they are constants

2024-04-12 18:11 UTC, binaryoverload commented on src/backend/metadata/tmdb.ts
> +    res = await mwFetch<any>(encodeURI(url), {
```suggestion
    res = await mwFetch<T>(encodeURI(url), {
```

2024-04-12 18:11 UTC, binaryoverload commented on src/backend/metadata/tmdb.ts
> +  let res: Promise<T>;
We're not returning a promise, we're returning the value itself as the promises are being awaited

```suggestion
  let res: T;
```

2024-04-12 18:11 UTC, binaryoverload commented on src/backend/metadata/tmdb.ts
> +      res = await mwFetch<any>(encodeURI(url), {
```suggestion
      res = await mwFetch<T>(encodeURI(url), {
```

2024-04-12 18:45 UTC, meghrathod commented on src/backend/metadata/tmdb.ts
> +let baseURL = "https://api.themoviedb.org/3";
okay, will do that

2024-04-12 18:47 UTC, meghrathod commented on src/backend/metadata/tmdb.ts
> +    if (baseURL !== otherUrl) {
no, they are not constants in this implementation and I set the baseURL as the other if we do the fallback. but as per @JorrinKievit's suggestion, I'll use boolean for this and implement it so yes then they will be constants

2024-04-14 10:50 UTC, meghrathod commented
@JorrinKievit made the required changes, review and let me know

2024-04-14 20:19 UTC, binaryoverload approved these changes

2024-04-14 20:21 UTC, merged

2024-04-22 08:47 UTC, ajay01994 commented
Hi @meghrathod  this  fall back option doesn't work for jio users .it doesn't  load alternate url ,do you any other solution to access TMDB in India ?

2024-04-22 08:52 UTC, binaryoverload commented
Please make a new issue for any problems