Download button
movie-web/movie-web pull request #157
Opened 2023-02-21 02:29 UTC by zisra

Adds an option to download the current show/movie

2023-02-21 14:33 UTC, mrjvs commented
will resolve #164 once merged

2023-02-21 14:41 UTC, mrjvs requested changes
on top of this, the downloading of m3u8 files will be decided with the rest of the dev team

2023-02-21 14:41 UTC, mrjvs commented on src/components/Icon.tsx
> +  download: `<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class
width and height needs to be set to 1em in the svg

2023-02-21 14:41 UTC, mrjvs commented on src/video/components/VideoPlayer.tsx
> +                      <DownloadAction />
Please place the icon left of the caption selector

2023-02-21 14:41 UTC, mrjvs commented on src/video/components/actions/DownloadAction.tsx
> +    <a href={sourceInterface.source?.url} download>
To prevent user tracking or the source finding out we are using them. add `rel="noreferrer"` and `target="_blank"`.

for more details see https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#security_and_privacy

2023-02-21 14:41 UTC, mrjvs commented on src/video/components/actions/DownloadAction.tsx
> +      />
on mobile it should have download text (and should also be visible on mobile in the first place)

2023-02-21 14:45 UTC, JamesHawkinss commented
need to handle HLS somehow

2023-02-21 15:12 UTC, mrjvs commented on src/video/components/actions/DownloadAction.tsx
> +    <a href={sourceInterface.source?.url} download>
Set the download attribute to the normalized title (see `src/utils/normalize.ts`) so that the downloaded file has the correct filename

2023-02-21 15:12 UTC, mrjvs commented
the HLS stuff can stay as it is for now, we will improve on it later

2023-02-21 20:21 UTC, zisra commented
I don't know why this doesn't work (undefined)
```js
const { isSeries, humanizedEpisodeId, meta } =  useCurrentSeriesEpisodeInfo(descriptor);
```

2023-02-21 20:26 UTC, JamesHawkinss requested changes

2023-02-21 20:26 UTC, JamesHawkinss commented on public/config.js
> +  VITE_CORS_PROXY_URL: "https://rough.isra.workers.dev",
Remove this

2023-02-21 20:28 UTC, mrjvs commented
> I don't know why this doesn't work (undefined)
> 
> ```js
> const { isSeries, humanizedEpisodeId, meta } =  useCurrentSeriesEpisodeInfo(descriptor);
> ```

instead use `useMeta`

2023-02-21 21:10 UTC, zisra commented
I cannot guarantee if it works just yet, please let me know if I did something wrong

2023-02-22 21:44 UTC, zisra commented on src/video/components/actions/DownloadAction.tsx
> +    <a href={sourceInterface.source?.url} download>
@mrjvs Should I include the season and episode number/name? If so, in what format?

2023-02-22 22:17 UTC, lem6ns commented on src/video/components/actions/DownloadAction.tsx
> +    <a href={sourceInterface.source?.url} download>
> @mrjvs Should I include the season and episode number/name? If so, in what format?

format I usually use (and many others) is S01E01

2023-02-24 21:35 UTC, mrjvs approved these changes

2023-02-24 21:35 UTC, merged