Add Picture-in-picture
movie-web/movie-web pull request #175
Opened 2023-02-27 07:21 UTC by zisra

Should close #174
**Q:** Would you prefer to hide or blur the PIP button if it is not available?

2023-02-27 07:41 UTC, mrjvs commented
Hiding the button is good.

It also needs support for safari: https://developer.apple.com/documentation/webkitjs/adding_picture_in_picture_to_your_safari_media_controls#2940030

2023-02-27 09:44 UTC, zisra commented
@mrjvs If the button is hidden if there is no support, would it make sense to make this consistent with the download button?

2023-02-27 09:50 UTC, mrjvs commented
With download, its the content that isn't supported, not the browser.

We hide functionality quite a lot if browser doesnt support: volume, fullscreen, chromecast, airplay.

2023-02-27 09:59 UTC, JamesHawkinss commented
This doesn't seem to be building

2023-02-28 15:32 UTC, JamesHawkinss requested changes
Still failing to build.

`12:23:20 PM: src/video/state/providers/castingStateProvider.ts(152,19): error TS2339: Property 'togglePictureInPicture' does not exist on type 'RemotePlayerController'.`

2023-02-28 15:32 UTC, JamesHawkinss commented on public/config.js
> +  VITE_CORS_PROXY_URL: "https://rough.isra.workers.dev",
Do not commit your proxy URL

2023-02-28 16:55 UTC, zisra commented on public/config.js
> +  VITE_CORS_PROXY_URL: "https://rough.isra.workers.dev",
I will fix it sorry

2023-02-28 19:05 UTC, zisra commented
This should work

2023-03-04 14:56 UTC, mrjvs requested changes
just a few changes needed.
I've tested everything except on safari.

2023-03-04 14:56 UTC, mrjvs commented on src/video/components/actions/PictureInPictureAction.tsx
> +      disabled={false}
remove disabled

2023-03-04 14:56 UTC, mrjvs commented on src/video/state/providers/castingStateProvider.ts
> +      updateSource(descriptor, state);
no need to update source if nothing happened

2023-03-04 14:56 UTC, mrjvs commented on src/video/state/types.ts
> +    isPictureInPicture: boolean; // is picture in picture active
the isPictureInPicture is not used anywhere, just remove it

2023-03-05 16:34 UTC, JamesHawkinss approved these changes

2023-03-10 19:29 UTC, mrjvs approved these changes

2023-03-10 19:29 UTC, merged