flixhq scraping improved
movie-web/movie-web pull request #199
Opened 2023-03-12 10:58 UTC by frost768

2023-03-12 21:56 UTC, mrjvs requested changes

2023-03-12 21:56 UTC, mrjvs commented on src/backend/helpers/streams.ts
> +  QAUTO = "auto",
why was QAuto added? it doesnt seem to be used

2023-03-12 22:26 UTC, mrjvs commented
tested, works great. just resolve the one review comment and it can be merged

2023-03-13 13:51 UTC, frost768 commented on src/backend/helpers/streams.ts
> +  QAUTO = "auto",
it does come from flixhq side so if we ever let users to choose their own preferred quality it is just an another option we can display to them

2023-03-13 18:39 UTC, frost768 commented on src/backend/helpers/streams.ts
> +  QAUTO = "auto",
ok, removed it.

2023-03-13 18:40 UTC, mrjvs approved these changes

2023-03-13 18:41 UTC, merged