Playback speed
movie-web/movie-web pull request #224
Opened 2023-03-23 18:52 UTC by zisra

2023-03-25 20:44 UTC, mrjvs commented
I cant find any feature requests for this on github or the discord server,
do you have a specific need for changing playback rate?

2023-03-25 21:28 UTC, zisra commented
I used an extension to do this previously because I like to be able to watch certain boring parts of an episode at a quicker speed. Also it is part of many standard video players

2023-03-30 22:19 UTC, mrjvs requested changes
a few more changes and then itll be ready for merge

2023-03-30 22:19 UTC, mrjvs commented on src/video/state/providers/castingStateProvider.ts
> +    },
Please dont make a recursive call lol.

use LoadRequest with a media object that has the proper playbackrate.

see https://developers.google.com/cast/docs/reference/web_sender/chrome.cast.media.LoadRequest

2023-03-30 22:19 UTC, mrjvs commented on src/video/state/providers/videoStateProvider.ts
> +    },
in addition to this, you will also need to listen to the playbackrate event on the video player element, thats in case extensions or native browser features allow the user to change the rate manually. It wont desync if we listen for those events.

see https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/ratechange_event

2023-03-30 23:27 UTC, zisra commented
Please don't merge yet, I'm making one more change

2023-03-31 00:10 UTC, zisra commented
Here we go

2023-03-31 16:55 UTC, frost768 commented
Could you use yarn instead of npm? In readme it states "note: must use yarn to install packages and run NodeJS 16"

2023-04-02 14:39 UTC, mrjvs requested changes
tested everything, seems to work great. just those two review comments left and it can be merged directly

2023-04-02 14:39 UTC, mrjvs commented on src/video/state/providers/videoStateProvider.ts
> +    },
forgot about it last review, but this will need to also call `updateMediaPlaying(descriptor, state);`

2023-04-02 14:39 UTC, mrjvs commented on yarn.lock
this lock file is now filled with npm registries.
please remove the lock file and replace it with the one copied from the dev branch.
also please use yarn in the future to avoid problems like this

2023-04-02 15:04 UTC, zisra commented
Done @mrjvs

2023-04-02 15:06 UTC, mrjvs commented
> Done @mrjvs

nice, however those import changes you breaks compilation.
please revert them

2023-04-09 11:21 UTC, mrjvs approved these changes

2023-04-09 11:22 UTC, merged