Better subtitle handling
movie-web/movie-web pull request #230
Opened 2023-03-26 12:20 UTC by frost768

- Added a new subtitle parser library
- File types are not limited to srt and vtt
- Fixes malformed subtitle files
- Clean up code

2023-03-30 22:28 UTC, mrjvs requested changes
nice job overal, just a few tid bits to fix.

2023-03-30 22:28 UTC, mrjvs commented on src/backend/helpers/streams.ts
> +  type?: MWCaptionType;
instead of making it nullable, please just add a "UNKNOWN" enum value.

2023-03-30 22:28 UTC, mrjvs commented on src/backend/helpers/captions.ts
> +  .join(",");
perhaps make this an array of file extensions instead of a string. You can join it when you pass it into the accept param of the file upload

2023-03-30 22:28 UTC, mrjvs commented on src/backend/helpers/captions.ts
> +    .map((cue) => cue as ContentCaption);
instead of mapping (which actually runs code). just cast the entire result of the filter so its just doing things in compilation.

2023-03-31 17:02 UTC, frost768 commented on src/backend/helpers/streams.ts
> +  type?: MWCaptionType;
I was going to remove it but left it. Reason is it is not used anywhere anymore. Also with this new library there aren't any limitations for subtitle file types.

2023-03-31 17:12 UTC, frost768 commented on src/video/components/popouts/CaptionSelectionPopout.tsx
>        controls.closePopout();
sometimes this doesn't close the popout considering adding a timeout. Should I?

2023-03-31 17:30 UTC, frost768 commented on src/backend/helpers/captions.ts
> +  .join(",");
wouldn't it run map on every render?

2023-03-31 17:33 UTC, mrjvs commented on src/backend/helpers/captions.ts
> +  .join(",");
I said to only do the joining inside the component. and yes it would. but joining is not expensive to run and realistically it wouldnt render that much at all. basically only when its open.

2023-04-02 14:44 UTC, mrjvs commented on src/backend/helpers/streams.ts
> +  type?: MWCaptionType;
I would still keep it, even if unused. its valuable information for if we ever switch sub library again or want to preprocess it or something. dont wanna lose the information.

2023-04-02 14:44 UTC, mrjvs commented on src/video/components/popouts/CaptionSelectionPopout.tsx
>        controls.closePopout();
yea sure, add a comment explaining why the timeout is tho

2023-04-02 14:45 UTC, mrjvs commented
I saw a few review comments resolved but no new commits. is that intentional?

2023-04-02 15:15 UTC, frost768 commented
> I saw a few review comments resolved but no new commits. is that intentional?

yeah used it as a reminder to myself that i edited them

2023-04-02 15:21 UTC, mrjvs approved these changes

2023-04-02 15:21 UTC, merged