Media session added
movie-web/movie-web pull request #238
Opened 2023-03-28 04:22 UTC by frost768

2023-03-30 22:45 UTC, mrjvs requested changes
See review comments, and also I have one question:

Do you think we also need to do the changes for the castingStateProvider?

2023-03-30 22:45 UTC, mrjvs commented on src/video/state/types.ts
> +        };
please keep it as only null or a value. lets not do both undefined and null, thats just confusing

2023-03-30 22:45 UTC, mrjvs commented on src/backend/metadata/justwatch.ts
> +  );
I think it's better to only have a single nullable backdrop url on the meta object instead of all backdrops.
we're only ever going to use the first one in the list anyway.

2023-03-30 22:45 UTC, mrjvs commented on src/video/components/internal/VideoElementInternal.tsx
> +      }
default it to `undefined` instead of empty string. with `undefined` the attribute will actually be unset by react instead of setting it to an empty string.

2023-03-31 18:24 UTC, frost768 commented on src/backend/metadata/justwatch.ts
> +  );
i thought we would use them but ok

2023-04-02 14:50 UTC, frost768 commented
> See review comments, and the linting errors.
> 
> Also I have one question: Do you think we also need to do the changes for the castingStateProvider?
> 
> and if we do need almost the exact same code for the chrome casting, maybe it can be moved to a renderless internal video component.

i don't own a casting device so i'm not sure how it works

2023-04-02 15:02 UTC, mrjvs commented
> i don't own a casting device so i'm not sure how it works

I think we'd need to do the same to the chrome casting state provider.
But thats best moved into a internal video component. itll just use the state stuff just like the actions to register the media session events. That way we also keep it modular, easy to change things in the future.

2023-04-09 11:27 UTC, mrjvs commented
As this PR has requested changes and haven't been modified for more than a week. I'm gonna close it, feel free to reopen or make a new PR when the changes have been made.

2023-04-09 11:27 UTC, closed without merging

2023-04-09 11:45 UTC, frost768 commented
I did change the code with suggested ones accordingly. Are you talking about moving it to a different component that is wrapped in videoplayerbase component?

2023-04-09 11:46 UTC, mrjvs commented
> I did change the code with suggested ones accordingly. Are you talking about moving it to a different component that is wrapped in videoplayerbase component?

yea, perhaps I wasn't clear enough that I think that should be done that way.
We should move the code from the stateProviders to an internal video component put in the base

2023-04-09 20:13 UTC, frost768 commented
Opened a new one with requested changes #254