A settings modal
movie-web/movie-web pull request #252
Opened 2023-04-06 09:17 UTC by frost768

This PR is for the the following issues
 #163 and #177 

- Settings modal
   - Language selection
   - Default subtitle language selection
   - Subtitle style change with a preview display

-  Fetch default subtitle with a retry mechanism

2023-04-06 09:40 UTC, frost768 commented
Desktop and mobile preview. Responsive in-between
![desktop](https://user-images.githubusercontent.com/19949367/230338040-ee94d9c0-30b1-4c07-aa9f-8fc1753d47a7.png)
![mobile](https://user-images.githubusercontent.com/19949367/230338034-ee9005d4-f378-43ea-b430-6462167840ec.png)

2023-04-09 12:17 UTC, mrjvs requested changes
looks good, just a few requests for code cleaniness.

I do think this needs a redesign in the future, a simple modal probably won't be enough if it grows.
But as it is right now, its plenty for a first version.

2023-04-09 12:17 UTC, mrjvs commented on src/video/components/actions/CaptionRendererAction.tsx
> +          : captionSettings.style.fontSize * scale,
I prefer doing it like this: `captionSettings.style.fontSize * ( scale ?? 1)`. Less conditional branches can be easier to read

2023-04-09 12:17 UTC, mrjvs commented on src/views/SettingsModal.tsx
> +    [captionSettings.language]
Please dont use non-null assertions

2023-04-09 12:17 UTC, mrjvs commented on src/views/SettingsModal.tsx
> +    [captionSettings.language]
same file at the dropdown there is another one

2023-04-09 12:17 UTC, mrjvs commented on src/views/SettingsModal.tsx
> +                    ))}
As the color swatch button is no longer used in only one place, I think its justified to make that a standalone component.

2023-04-09 12:17 UTC, mrjvs commented on src/views/SettingsModal.tsx
> +                ) : null}
I think that we should still show a caption cue preview even if the preferred caption language is unset. just use `lorem ipsum` as some placeholder text if the language isnt set

2023-04-09 12:17 UTC, mrjvs commented on src/views/SettingsModal.tsx
> +  const colors = ["#ffffff", "#00ffff", "#ffff00"];
this is now used in two places, please put it in a file somewhere so we don't have the same constant color definitions is two places

2023-04-09 12:17 UTC, mrjvs commented on src/views/SettingsModal.tsx
Can you add the version number of the app to the settings modal somewhere, that way we fully resolve #163.
You can use the `conf()` function to get it.

2023-04-09 20:21 UTC, frost768 commented on src/views/SettingsModal.tsx
> +                ) : null}
i think we should not because it represents how it will look like in video player. it sounds silly but some may think that it will show a text even if a caption is not selected

2023-04-09 20:30 UTC, frost768 commented on src/views/SettingsModal.tsx
> +                    ))}
should we also move colors array into this component? it will only be used in this.

2023-04-09 20:33 UTC, frost768 commented on src/video/components/actions/CaptionRendererAction.tsx
> +      ].join(" ")}
i was trying to use classes for scaling but you are right it is not necessary anymore

2023-04-09 20:37 UTC, mrjvs commented on src/views/SettingsModal.tsx
> +                    ))}
I wouldn't, however you can put the constant export into the same file as the component

2023-04-09 21:02 UTC, frost768 commented on src/views/SettingsModal.tsx
> +                    ))}
what about other caption settings? they all use slider component should i also extract them to their own component?

2023-04-09 21:58 UTC, zisra commented
Would it make sense to add playback speed?

2023-04-09 22:00 UTC, frost768 commented
> Would it make sense to add playback speed?

without a dummy video, i dont think so

2023-04-14 18:23 UTC, mrjvs commented on src/views/SettingsModal.tsx
> +                    ))}
I don't think we should make the block of sliders a component. just do the colorSwatch button and constant export for the color list.

2023-04-14 18:23 UTC, mrjvs commented
> what would be nice as well is to change the homepage dropdown default, I personally don't really watch movies, so I think being able to set series as default for the search bar would be nice

Please make that a new issue, its not in scope for this PR

2023-04-20 18:32 UTC, mrjvs requested changes
looks good, just change the denim-200 to denim-300 for the background and then its all done

2023-04-20 18:56 UTC, mrjvs approved these changes

2023-04-20 18:56 UTC, merged