Media session component
movie-web/movie-web pull request #254
Opened 2023-04-09 20:12 UTC by frost768

Subsequent to PR #238
Moved media session logic into its own component

2023-04-14 18:17 UTC, mrjvs requested changes
just one change to prevent it breaking unexpectedly

2023-04-14 18:17 UTC, mrjvs commented on src/video/components/internal/MediaSessionInternal.tsx
> +  }, [state.stateProvider]);
this will break at changes in meta data or similar.
What you can do is make a media session once with this component (0 dependencies). put it in a ref.
then use a bunch of useEffects to update the metadata in the session or update a few refs.

You can use refs freely in effects without adding them to the dependency array.

So in short:
 - one effect to make the session, store it in a ref
 - useEffect on meta data to update the media session ref
 - useEffect on useControls and useProgress and store both in refs
 - the media session handlers can use the progress and controls refs to control things

2023-04-14 22:58 UTC, frost768 commented on src/video/components/internal/MediaSessionInternal.tsx
> +  }, [state.stateProvider]);
meta updates with progress. if i use meta as a dependency it will run every second causing media session metadata to change along with it.

2023-04-14 23:00 UTC, mrjvs commented on src/video/components/internal/MediaSessionInternal.tsx
> +  }, [state.stateProvider]);
you can memoize the only the metadata you use and use that as a dependency

2023-04-14 23:14 UTC, frost768 commented on src/video/components/internal/MediaSessionInternal.tsx
> +  }, [state.stateProvider]);
yeah you can but the memoized version will be watching the original one for changes hence it will trigger no matter what

2023-04-20 18:36 UTC, mrjvs commented on src/video/components/internal/MediaSessionInternal.tsx
> +  }, [state.stateProvider]);
its a bit jank, but if you stringify before memoing, it will only trigger on change `useMemo(() => JSON.stringify({ postUrl: "" }))`

2023-12-19 20:19 UTC, mrjvs commented
Pull request is out of date with v4. Closing

(sorry that I never got it again)

2023-12-19 20:19 UTC, closed without merging