Time format
movie-web/movie-web pull request #255
Opened 2023-04-11 21:17 UTC by zisra

2023-04-11 21:19 UTC, zisra commented
<img width="530" alt="Screenshot 2023-04-11 at 4 19 32 PM" src="https://user-images.githubusercontent.com/100528712/231290637-8b7372ab-4e6e-4110-9851-0d19434bd654.png">
Looks like this

2023-04-14 17:56 UTC, mrjvs requested changes

2023-04-14 17:56 UTC, mrjvs commented on src/video/state/types.ts
>    };
use an enum for these possible, never use magic numbers.

2023-04-14 17:56 UTC, mrjvs commented on src/video/state/providers/videoStateProvider.ts
> +    },
add this method to the `controls.ts` file, not to the state providers (as the format of the time has nothing to do with how the video is played)

2023-04-14 17:56 UTC, mrjvs commented on src/video/state/logic/interface.ts
> +    },
dont add methods to state only objects, when you've added to the controls.ts file, you can do useControls to access the method.

2023-04-14 17:56 UTC, mrjvs commented on src/video/components/actions/TimeAction.tsx
> +            {/* {time} {props.noDuration ? "" : `/ ${duration}`} */}
please remove the comment

2023-04-14 17:56 UTC, mrjvs commented on src/video/components/actions/TimeAction.tsx
> +      ].join(" ")}
dont offset the by -16 pixels, just remove it

2023-04-14 17:56 UTC, mrjvs commented on src/video/components/actions/TimeAction.tsx
> +                } `}
for mobile (`useIsMobile()`). only display the time left with negative sign in front for the second time format.
Also this conditional may be worth putting in a variable with normal if statements, its getting quite hard to read

2023-04-14 17:56 UTC, mrjvs commented on src/video/components/actions/TimeAction.tsx
> +  );
don't forget about the hasHours parameter, right now it doesn't show hours in time left

2023-04-14 18:31 UTC, zisra commented on src/video/components/actions/TimeAction.tsx
> +      ].join(" ")}
The 16px makes it look exactly the way it looked before my changes, and If I were to remove it the time would be way far too the right

2023-04-14 18:34 UTC, mrjvs commented on src/video/components/actions/TimeAction.tsx
> +      ].join(" ")}
it looks wonky on mobile, so I think its best to remove it

2023-04-14 19:15 UTC, zisra commented on src/video/state/logic/interface.ts
> +    },
"React Hook "useControls" cannot be called at the top level. React Hooks must be called in a React function component or a custom React Hook function."

2023-04-14 19:18 UTC, zisra commented
Not sure whether this fixes it or not. Sorry if I did it wrong

2023-04-20 18:57 UTC, mrjvs approved these changes

2023-04-20 19:04 UTC, merged