Add serverf4 provider
movie-web/movie-web pull request #262
Opened 2023-04-15 04:02 UTC by zisra

**This should be working (tested with no-CORS extension) but there is one issue:**
- The provider needs to make a request to an URL, not to read the contents, but to see what URL it finally redirects to. 
- Usually when requesting a URL with redirects, the fetch api would return an object that contains the final URL including redirects. 
- But when using a CORS proxy, redirects are handled by the proxy and the final URL is the same as the URL requested
**Possible solutions**
- Don't handle redirects with the proxy and make the client handle them
- Add a `X-Final-Destination` header to the response

2023-04-15 19:46 UTC, mrjvs commented
Nice work, good find.

For the proxy issues, I think it's best we make an extra header `X-Disable-Redirect-Following: "true"`.
we have a repository for the proxy here: https://github.com/movie-web/simple-proxy, if you feel up for it, you can PR it there. should be a one-liner.

2023-04-15 19:50 UTC, mrjvs requested changes

2023-04-15 19:50 UTC, mrjvs commented on src/backend/helpers/fetch.ts
> +): R<T> {
I think it's better to have a `rawProxiedFetch(url, ops): FetchResponse<any>` instead of modifying the original one with a boolean option.

2023-04-15 19:50 UTC, mrjvs commented on src/backend/helpers/fetch.ts
> +): R<T> {
That would also fix the type errors

2023-04-15 19:50 UTC, mrjvs commented on src/backend/providers/serverf4.ts
> +
make a specific check if there are no files and throw a error, much like the no iframe error. that way its easier to trace what the problem is when it fails

2023-04-15 21:02 UTC, zisra commented on src/backend/helpers/fetch.ts
> +): R<T> {
I'm having trouble with this and can't figure out how to fix this redirect thing, sorry

2023-04-22 02:12 UTC, zisra commented
Not sure what happened to serverf4.org but it's gone

2023-04-22 02:12 UTC, closed without merging