Add French in the settings languages selector
movie-web/movie-web pull request #272
Opened 2023-04-22 11:36 UTC by judemont

Hello, 
I added French in the language selector of the settings.
I also updated the French translation.

2023-04-22 13:55 UTC, BrightDV reviewed
Only small typos, otherwise, looks great!

2023-04-22 13:55 UTC, BrightDV commented on src/setup/locales/fr/translation.json
> +      "back": "Eevenir en arrière",
```suggestion
      "back": "Revenir en arrière",
```

2023-04-22 13:55 UTC, BrightDV commented on src/setup/locales/fr/translation.json
> +      "customPlaybackSpeed": "Custom playback speed",
```suggestion
      "customPlaybackSpeed": "Vitesse de lecture personnalisée",
```

2023-04-22 13:55 UTC, BrightDV commented on src/setup/locales/fr/translation.json
> +    "genericTitle": "Not found",
```suggestion
    "genericTitle": "Introuvable",
```

2023-04-22 14:50 UTC, judemont commented
> Only small typos, otherwise, looks great!

It's done, thanks

2023-04-23 11:51 UTC, JamesHawkinss requested changes

2023-04-23 11:51 UTC, JamesHawkinss commented on src/setup/locales/fr/translation.json
> +      "back": "Revenir en arrière",
This is quite a long string, suggesting `Retourner` as an alternative

2023-04-23 11:52 UTC, JamesHawkinss commented on src/setup/locales/fr/translation.json
> +      "back": "Revenir en arrière",
```suggestion
      "back": "Retourner",
```

2023-04-23 11:52 UTC, JamesHawkinss commented on src/setup/locales/fr/translation.json
> +      "back": "Revenir en arrière",
This is quite a long string, suggesting Retourner as an alternative

2023-04-23 17:06 UTC, JamesHawkinss approved these changes

2023-04-23 17:06 UTC, merged