Czech language
movie-web/movie-web pull request #280
Opened 2023-04-25 14:40 UTC by panmlg

2023-04-25 14:53 UTC, mrjvs commented
please see the code style annotations. (click "files changed" tab on this page)

2023-04-25 15:01 UTC, panmlg commented
> please see the code style annotations. (click "files changed" tab on this page)

I apologize, didn't see that. Hopefully it's better now.

2023-04-25 15:03 UTC, mrjvs commented
code style is good now, thanks. I'll verify the translations later today.

2023-04-26 09:49 UTC, JamesHawkinss requested changes
Don't translate the keys!

2023-04-26 09:49 UTC, JamesHawkinss commented on src/setup/locales/cs/translation.json
> +    "seasonAndEpisode": "S{{sezóna}} E{{epizoda}}"
```suggestion
    "seasonAndEpisode": "S{{season}} E{{episode}}"
```

2023-04-28 08:28 UTC, JamesHawkinss approved these changes

2023-05-06 09:19 UTC, merged