fix: BackdropAction.tsx component render issue
movie-web/movie-web pull request #297
Opened 2023-05-17 18:38 UTC by yilmazcabuk

This pull request includes the following changes:

1. **fix: fix an issue with BackdropAction component**

   The commit addresses issue #296 and includes the following changes:
   - Importing the `RefObject` type from "react" in addition to the existing imports.
   - Adding the `useIdle` hook from "react-use" as a new import.
   - Updating the `BackdropOverlay` component to use the `useMemo` hook for generating the overlay classes.
   - Refactoring the `handleMouseMove` function to use a timeout for setting the `moved` state.
   - Removing the timeout when the mouse leaves the component using the `handleMouseLeave` function.
   - Modifying the `handleClick` function to use the `handleClickOrTouch` utility function for handling mouse and touch events.
   - Modifying the `BackdropAction` component to receive the `onBackdropChange` prop and the `children` prop.
   - Updating the component to use the new `useIdle` hook.
   - Refactoring the `useEffect` hook to update the `onBackdropChange` callback when the `isVideoOverlayVisible` state changes.
   - Using the `useMemo` hook to generate the `overlayWrapperClasses` based on the `isVideoOverlayVisible` state.
   - Renaming the `showUI` variable to `isVideoOverlayVisible` for clarity.
   - Updating the JSX structure to incorporate the changes in the `BackdropOverlay` component and the `overlayWrapperClasses`.

   This commit improves the BackdropAction component.

2. **refactor: sort ESLint rules alphabetically**

   The ESLint rules in the `.eslintrc.js` file have been sorted alphabetically to improve readability and maintainability. Specifically, the `@typescript-eslint/consistent-type-exports` rule has been moved to its correct alphabetical position.

   Changes:
   - Moved `@typescript-eslint/consistent-type-exports` to its correct alphabetical position.

3. **refactor: update BackdropAction.tsx to use type imports**

   The `BackdropAction` component has been updated to use the `ReactNode` type instead of `React.ReactNode` and to use the `MouseEvent` and `TouchEvent` types instead of `React.MouseEvent` and `React.TouchEvent`. This change was made to improve type safety and consistency throughout the codebase.

   Changes:
   - Imported the `ReactNode` and `MouseEvent/TouchEvent` types from the "react" library.
   - Updated the `children` prop type to use `ReactNode`.
   - Updated the `handleClick` and `handleDoubleClick` event handlers to use `MouseEvent/TouchEvent` types.

4. **fix: Add key prop to CaptionColorSelector component**

   This commit adds a `key` prop to the `CaptionColorSelector` component to improve its performance and avoid warning messages. The `key` prop is set to the value of the `color` prop, ensuring that each instance of the component is uniquely identified.

5. **refactor: add type imports**

   This commit adds TypeScript type imports to the project, which will help ensure type safety and better error handling throughout the codebase. Specifically, "import type" statements have been added for modules that are used purely for types.

6. **refactor: sort ESLint rules alphabetically**

   Previously, the ESLint rules in the codebase were not sorted, which made it difficult to locate specific rules or ensure consistency. This commit refactors the rules to be sorted alphabetically, making them easier to navigate and manage.

Please review and merge this pull request into the `dev` branch.

2023-05-18 18:16 UTC, zisra commented
Professional GitHub user 👍

2023-05-19 18:53 UTC, mrjvs requested changes
Hey, just a few changes.

I must also ask you to not make major refactors that often, they are quite a handful to review and test. Most times it just not worth the effort, like sorting eslint rules, the benefit isnt great enough to really matter.

If you do refactor something, please keep it to one refactor per PR. having 99 changed files makes this really hard to search through.

I'll let it go through this time (provided you resolve the issues mentioned). But please keep this in mind for next time.

2023-05-19 18:53 UTC, mrjvs commented on src/components/layout/Navigation.tsx
> +  useKeyPressEvent("Escape", handleSettingsModalClose);
this should be a prop on the Modal component rather than being outside of it.

also, this doesn't work, every click on the modal immediately closes it, rendering it unusable

2023-05-19 18:53 UTC, mrjvs commented on src/hooks/useEventListener.ts
Was this written by you? seems very verbose and unneccesarily complex.

2023-05-19 18:53 UTC, mrjvs commented on src/hooks/useIsomorphicLayoutEffect.ts
> +  typeof window !== "undefined" ? useLayoutEffect : useEffect;
why?

2023-05-19 18:53 UTC, mrjvs commented on src/video/components/actions/BackdropAction.tsx
few things broken about this backdrop:
 - touch controls should only open the backdrop, not also trigger a pause.
 - leaving the browser window doesn't close the backdrop
 - 1 second interval is too short, keep it as it was
 - dropin shadows are broken, they are always at the top without any gradient.
 
 Next time, I implore you to throroughly test your changes.

2023-05-20 12:06 UTC, yilmazcabuk commented on src/hooks/useIsomorphicLayoutEffect.ts
> +  typeof window !== "undefined" ? useLayoutEffect : useEffect;
This is useful for tasks that require immediate access to the updated DOM, such as measuring elements or performing animations. But since we use `react-use` library, we don't need it, so this and other hooks added are removed already.

2023-05-20 12:07 UTC, yilmazcabuk commented on src/hooks/useEventListener.ts
Since we have the same hook in `react-use` library, it's removed.

2023-05-20 16:04 UTC, yilmazcabuk commented on src/components/layout/Navigation.tsx
> +  useKeyPressEvent("Escape", handleSettingsModalClose);
May I ask, why we're not using [HeadlessUI - Dialog](https://headlessui.com/react/dialog) for `Settings` modal? I fixed the problem but for future additions, it would be better to have a consistent component.

2023-05-20 16:32 UTC, mrjvs commented on src/components/layout/Navigation.tsx
> +  useKeyPressEvent("Escape", handleSettingsModalClose);
We had some specific requirements for the modal, and the headlessui one was too restrictive.

So we made our own Modal component.

2023-05-23 18:25 UTC, closed without merging