Add T query param for time and make scrollbar styles global
movie-web/movie-web pull request #306
Opened 2023-05-25 20:59 UTC by JipFr

- Add support for a `t` query param, allowing people to share links with a specific time. Supports both seconds (like how YouTube does it, say `t=530` and MM:SS and HH:MM:SS, e.g `?t=1:20:05`
- Make scrollbar styles global

2023-05-25 22:36 UTC, binaryoverload requested changes

2023-05-25 22:36 UTC, binaryoverload commented on src/video/components/controllers/ProgressListenerController.tsx
> +      );
Jank

2023-05-25 22:36 UTC, binaryoverload commented on src/video/components/controllers/ProgressListenerController.tsx
> +      );
If you reverse the array instead, then you will be able to use natural indexing

2023-05-25 22:39 UTC, binaryoverload submitted a review, later dismissed
I can now wholeheartedly endorse this PR

2023-05-26 20:27 UTC, mrjvs commented on src/hooks/useQueryParams.ts
> +    }
any reason why you dont just `return new UrlSearchParams(loc.search)`?

2023-05-26 21:05 UTC, JipFr commented on src/hooks/useQueryParams.ts
> +    }
Only because I did not know it was a thing :P

2023-05-26 21:07 UTC, mrjvs approved these changes

2023-05-26 21:12 UTC, merged