Show more context on settings menu
movie-web/movie-web pull request #309
Opened 2023-05-26 04:26 UTC by zisra

<img width="325" alt="Screenshot 2023-05-25 at 11 24 00 PM" src="https://github.com/movie-web/movie-web/assets/100528712/989f0284-85fa-4815-adbf-bff6d3c1f4bd">

Captions and Playback speed now show more info. I believe this is important because it actually makes the user experience simpler. Users would have to click less buttons to see what current subtitle they are using. I implemented this because I felt like I needed it personally, so maybe others will too.

2023-05-26 04:59 UTC, frost768 commented
Never felt the need for it until I saw it and now I think it is a must

2023-05-26 11:25 UTC, JamesHawkinss requested changes

2023-05-26 11:25 UTC, JamesHawkinss commented on src/video/components/actions/list-entries/CaptionsSelectionAction.tsx
> +        {captionName ?? "None"}
I think if there are no captions, there should be no additional information displayed. Only show the language if there is a language to show.

2023-05-26 11:25 UTC, JamesHawkinss commented on src/video/components/actions/list-entries/PlaybackSpeedSelectionAction.tsx
> +import { useMeta } from "@/video/state/logic/meta";
See the linting errors here, 

'useMeta' is defined but never used
'useSource' is defined but never used

Will fail to lint, please fix!

2023-05-26 11:25 UTC, JamesHawkinss commented on src/video/components/actions/list-entries/QualityDisplayAction.tsx
This file still exists, is causing more lint errors

2023-05-26 13:06 UTC, zisra commented
Before I make this ready to merge, there are two alternatives that I have in mind:
- Keeping the chevron on all items
- Showing the current source for source (Because the source is not 720p, it's SuperStream) and the quality for download

2023-05-27 08:55 UTC, JamesHawkinss commented on src/video/components/actions/list-entries/DownloadAction.tsx
> +        {source.source.quality}
Consider hiding quality if it's of type UNKNOWN

2023-05-27 23:14 UTC, zisra commented
@JipFr Done. Looks like this now:
<img width="327" alt="Screenshot 2023-05-27 at 6 13 59 PM" src="https://github.com/movie-web/movie-web/assets/100528712/e7f01959-6212-46fc-b85f-c4fec530b0e9">
I also added support to download m3u8 files if that's ok. It's useful for me because I can use ffmpeg to later convert

2023-05-28 07:18 UTC, genolith commented
Can you add a option to choose video quality?

2023-05-28 07:40 UTC, JamesHawkinss requested changes
Have you checked that the design is fine on mobile?

2023-05-28 07:40 UTC, JamesHawkinss commented on src/video/components/actions/list-entries/CaptionsSelectionAction.tsx
> +      noChevron={!!captionName} // TODO: Make this false if <CurrentCaption /> returns null
Complete the TODO please

2023-05-28 07:40 UTC, JamesHawkinss commented on src/video/components/actions/list-entries/DownloadAction.tsx
> +import { MWStreamQuality, MWStreamType } from "@/backend/helpers/streams";
'MWStreamType' is defined but never used

2023-07-23 10:39 UTC, binaryoverload commented
Since this will be re-designed, we'll be shutting this PR as it won't be able to be used in v4.

2023-07-23 10:39 UTC, closed without merging