Thumbnails
movie-web/movie-web pull request #322
Opened 2023-06-08 01:10 UTC by frost768

Related to #223

2023-06-14 05:16 UTC, thehairy requested changes

2023-06-14 05:16 UTC, thehairy commented on src/utils/thumbnailCreator.ts
> +  const metadata = await new Promise((resolve, reject) => {
```suggestion
  await new Promise((resolve, reject) => {
```

metadata is not used, linter is complaining.

2023-06-15 11:45 UTC, thehairy approved these changes

2023-06-17 18:40 UTC, mrjvs commented on src/utils/thumbnailCreator.ts
> +export default async function* extractThumbnails(
first time I've ever seen a generator function used in the wild, exciting

2023-06-17 18:47 UTC, frost768 commented on src/utils/thumbnailCreator.ts
> +export default async function* extractThumbnails(
Yeah, this was the first time I used it in a project. It really made sense to use it. Waiting for every thumbnail to load would be a bad ux

2023-06-17 19:01 UTC, mrjvs requested changes
Nice job, just a few things missing.
I'm gonna retarget the PR to the v4 branch as its on the feature list for that version.

If you need assistance with the requested changes, we can also merge the incomplete PR and then I will finish it up.

2023-06-18 14:16 UTC, frost768 commented on src/utils/thumbnailCreator.ts
> +  canvas.width = video.videoWidth * SCALE_FACTOR;
For this I will create an interface and implement it for hls and mp4 videos.
Hls one will have the same logic:
1. Create an instance of hls with the video source
2. Listen to corresponding metadata and seek events in hls js lib and seek to desired tims with hls controller
3. Convert fragment array data into base64 data url

Also an abortcontroller to cancel future requests

2023-06-18 16:54 UTC, mrjvs commented on src/utils/thumbnailCreator.ts
> +  canvas.width = video.videoWidth * SCALE_FACTOR;
sounds good. A tip for the aborting. if you make it an internal video component. (which are just components of the video player that are always present) you can use useEffect to detect when the videoplayer has unloaded. Its also a good place to keep a video element always loaded (and hidden). a bit more efficient than making a new video element everytime.

2023-07-23 09:53 UTC, mrjvs commented
because the video player code will get a rewrite very soon for the new design, I'm gonna merge this now so the thumbnail component get roped in with the rewrite.

only thing missing was the design anyway, so good timing

2023-07-23 09:53 UTC, mrjvs approved these changes

2023-07-23 09:53 UTC, merged