feat(provider): streamflix
movie-web/movie-web pull request #324
Opened 2023-06-11 16:45 UTC by lem6ns

aka just 2embed LOL

tested tv and movies, subtitles work on both
glorified 2embed

2023-06-11 16:57 UTC, thehairy requested changes

2023-06-11 16:57 UTC, thehairy commented on src/backend/providers/streamflix.ts
> +        }
```suggestion
      const streamRes = await proxiedFetch<any>(
        `/api/player/tv`,
        {
          baseURL: streamflixBase,
          params: {
              id: media.tmdbId,
              s: seasonNumber,
              e: episodeNumber
          },
        }
```

You can also just set the seasonNumber and episodeNumber to 1 if its a movie, or keep it undefined.
Then you dont need such a huge if/else with basically the same code repeating

2023-06-11 18:00 UTC, thehairy requested changes

2023-06-11 18:00 UTC, thehairy commented on src/backend/providers/streamflix.ts
> +    let episodeNumber: any;
```suggestion
    let seasonNumber: string | undefined;
    let episodeNumber: string | undefined;
```

any just hurts my soul

2023-06-11 18:00 UTC, thehairy commented on src/backend/providers/streamflix.ts
> +    if (!streamRes.headers.Referer) throw new Error("No watchable item found");
Are you sure thats a reliable way to tell if there is a video?
Haven't looked that deep into the provider.

2023-06-11 19:19 UTC, lem6ns commented on src/backend/providers/streamflix.ts
> +    if (!streamRes.headers.Referer) throw new Error("No watchable item found");
> Are you sure thats a reliable way to tell if there is a stream?
> Haven't looked that deep into the provider.

YES! If referer is blank, there is no streams/captions

2023-06-11 19:20 UTC, lem6ns commented on src/backend/providers/streamflix.ts
> +    let episodeNumber: any;
Lol

2023-06-11 20:14 UTC, thehairy approved these changes

2023-06-11 20:17 UTC, thehairy approved these changes

2023-06-17 18:19 UTC, mrjvs approved these changes

2023-06-17 18:19 UTC, merged