feat: human readable urls & quicksearch
movie-web/movie-web pull request #364
Opened 2023-06-23 09:09 UTC by castdrian

This pr closes #342 and also closes #349 by implementing the following:

- urls get the slugified media title appended, which is purely cosmetic
`/media/tmdb-show-103516` -> `/media/tmdb-show-103516-star-trek-strange-new-worlds`

- new endpoint /s/:query automatically searches and plays the first result for the provided query
`/s/smallville` -> `/media/tmdb-show-4604-smallville`

2023-06-23 09:36 UTC, binaryoverload approved these changes
This looks good to me, it just needs testing by us.

2023-06-29 18:29 UTC, mrjvs requested changes
Just one tiny thing, for the rest it looks good. nice job.

2023-06-29 18:29 UTC, mrjvs commented on src/backend/metadata/getmeta.ts
> +    })}`;
I think you should have a function for this instead. Something like `TMDBIdToUrlId(type, tmdbId, title)`.
You should then also use it in `TMDBMediaToId()`. So there is only one place that makes urls, makes it easier to change later

2023-06-29 18:30 UTC, castdrian commented on src/backend/metadata/getmeta.ts
> +    })}`;
good catch, will do :)

2023-06-29 19:40 UTC, mrjvs approved these changes

2023-06-29 19:40 UTC, merged