feat: multisearch & opensearch & sitelinks
movie-web/movie-web pull request #376
Opened 2023-06-30 19:49 UTC by castdrian

this pr closes #350 by implementing:

- [x] multisearch
- [x] fix forgotten JW -> TMDB content type change
- [x] add ~dynamic~ opensearch support
- [x] add google sitelinks support

I tried to get the opensearch plugin to be dynamic for multiple hostnames but it seems to be impossible without SSR, unfortunately the browser doesn't care if it is modified client side

2023-06-30 19:58 UTC, mrjvs commented
Hmm, I dont really like hardcoding the domain. I'll research some compile template langs we can use.

That way we can disable the opensearch stuff for precompiled releases. And for compiled we can have an env var.

I'll get back to you on how to do it.

2023-06-30 20:01 UTC, castdrian commented
thank you I feel the same way, I tried for a couple hours with react and it was frustrating to say the least

2023-06-30 20:06 UTC, mrjvs requested changes
Didn't look at everything yet, just some initial thoughts

2023-06-30 20:06 UTC, mrjvs commented on src/backend/metadata/getmeta.ts
> +  }
Can you elaborate on why you switched from show to TV?

2023-06-30 20:10 UTC, castdrian commented on src/backend/metadata/getmeta.ts
> +  }
show was the JW content type, not the tmdb content type, was kinda overlooked during the refactor and ended up needing double conversion with multiseearch since it returns the content type, so I figured the correct action would be to actually make the tmdbcontent type type the actual values that tmdb uses instead of a double conversion

2023-06-30 20:13 UTC, mrjvs commented on src/backend/metadata/getmeta.ts
> +  }
Fair, sounds logical

2023-07-03 19:09 UTC, mrjvs requested changes
second batch, looked at everything this time :P

2023-07-03 19:09 UTC, mrjvs commented on public/opensearch.xml
I've tested the opensearch and spaces become "+" characters. This is same behaviour as query params. so we should make a query param for search. You can just redirect it to /browse/:keyword immediately. and choose a seperate url for opensearch.

2023-07-03 19:09 UTC, mrjvs commented on index.html
I've looked at templating engines, closest thing I could find is vituum: https://vituum.dev/
I think using handlebars is best. And instead of a pages directory you can put it in /src/assets. An asset folder is convention is preprocessed assets in these kinds of projects.

From experience, these kinds of builds steps can be tricky to configure. if you need help with it, let me know.

2023-07-03 19:12 UTC, zisra commented
Why are we using browse exactly? Search makes more sense to me because it does exactly what it says

2023-07-03 19:15 UTC, mrjvs commented
> Why are we using browse exactly? Search makes more sense to me because it does exactly what it says

because `/search/:type/:keyword` was the old one, so if you just change to `/search/:keyword`. all old backlinks wouldnt be the homepage anymore, it would search for `movie` or `series`.

having `/browse` would keep compatibility with old urls as we can redirect them properly

2023-07-03 19:16 UTC, mrjvs commented
We've discussed this with the maintainers and decided /browse is the best option

2023-07-03 19:33 UTC, zisra commented on index.html
Wouldn't this be possible using react-helmet?

2023-07-03 19:49 UTC, mrjvs commented on index.html
no, react-helmet does things on runtime. meta tags and structured data need to exist at compile time.

2023-07-04 06:40 UTC, castdrian commented on src/setup/App.tsx
> +                </Route>
could you elaborate a teensy tiny microscopic bit as to where it should point to, the original route config redirects root to search so I just copied that behaviour

2023-07-04 11:31 UTC, castdrian commented on index.html
it seems like the vituum handlebars plugin is incompatible with the version of vite that the project uses, so I'm kinda stumped

2023-07-04 11:49 UTC, mrjvs commented on src/setup/App.tsx
> +                </Route>
we're changing from how it originally was, too many people linked to /search/movie instead of main domain.

If no keyword is entered. it should be on `/`. if something is being searched, it should be on `/browse/:keyword`

2023-07-04 11:51 UTC, mrjvs commented on src/setup/App.tsx
> +                </Route>
You can do that with `<Route path={["/", "/browse/:keyword"]}>...</Route>`

2023-07-22 19:17 UTC, castdrian commented
oki doki, so it now reads APP_DOMAIN as env var and sets the opensearch accordingly, so should work with both dev and prod deployments, and localhost ofc

2023-07-22 19:26 UTC, mrjvs requested changes

2023-07-22 19:26 UTC, mrjvs commented on vite.config.ts
> +        appdomain: process.env.APP_DOMAIN,
I recommend using vite's environment loading instead of dotenv.

```js
import { loadEnv } from "vite"

export default defineConfig(({ mode } => ({
  plugins:[
    handlebars({
      vars: {
        env: loadEnv(mode, process.cwd()),
      }
    })
  ],
  ...
}))
```

2023-07-22 19:26 UTC, mrjvs commented on vite.config.ts
> +        appdomain: process.env.APP_DOMAIN,
it would load all the env starting with VITE_. so VITE_X would make the object { x: ... }.
Just like we have with all the other environment variable config so far.

2023-07-22 19:26 UTC, mrjvs commented on vite.config.ts
> +        appdomain: process.env.APP_DOMAIN,
also please document it in an example.env

2023-07-22 19:54 UTC, castdrian commented on vite.config.ts
> +        appdomain: process.env.APP_DOMAIN,
oki doki, one and done

2023-07-22 20:21 UTC, mrjvs requested changes
final batch of changes, I apologize for the amount of them.

2023-07-22 20:21 UTC, mrjvs commented on src/assets/opensearch.xml.hbs
> +  <Url type="text/html" template="{{ appdomain }}/browse/{searchTerms}" />
The searchTerm needs to be in a query parameter. lets do `/browse/?q={searchTerms}`.
The q param should automatically redirect to `/browse/{queryHere}`.
You can add this redirection as a hook in the home view itself.

2023-07-22 20:21 UTC, mrjvs commented on src/assets/opensearch.xml.hbs
> +  <Url type="text/html" template="{{ appdomain }}/browse/{searchTerms}" />
Same comment applies to the structured data for google search bar in the index.html

2023-07-22 20:21 UTC, mrjvs commented on src/setup/App.tsx
> +                </Route>
This redirection doesn't work. it just puts `:query` directly in the URL.

2023-07-22 20:21 UTC, mrjvs commented on src/setup/App.tsx
> +                <Route path={["/", "/browse/:query"]} component={SearchView} />
I think I've said before to put the path as a list. but turns out that doesn't work.
Make it two seperate routes, rendering the same component. the one with `/` needs that have the `exact` prop.

2023-07-22 20:21 UTC, mrjvs commented on vite.config.ts
This file now has a mix of tabs and spaces for indention. Please use only spaces, with size set to 2.

2023-07-22 20:21 UTC, mrjvs commented on index.html
> +		</script>
This also needs to be toggled with the OPENSEARCH_ENABLED env.

2023-07-22 20:21 UTC, mrjvs commented on index.html
> +    {{{ opensearch }}}
Please use handlebars if statement instead of injecting raw HTML.

See this documentation: https://handlebarsjs.com/guide/builtin-helpers.html#if

2023-07-22 20:21 UTC, mrjvs commented on src/components/SearchBar.tsx
> -        </DropdownButton>
the i18n key `searchBar.search` can now be removed from the locale files

2023-07-22 20:21 UTC, mrjvs commented on src/setup/App.tsx
> +                <Route path={["/", "/browse/:query"]} component={SearchView} />
With the new url. search terms in the url seems to have broken.
previous behaviour:
 - on page load, it wil load in the query from the url and insert it into the searchbar.
 - on unfocus of the searchbar, the query that was typed in would be added to the url.

this functionality is still implemented, just needs to be adapted to work with the new url.

2023-07-22 20:21 UTC, mrjvs commented on example.env
> +VITE_APP_DOMAIN="http://localhost:5173"
please remove the quotes around the value and add a comment saying it should be without a slash at the end of the url. (similar to the cors proxy url comment

2023-07-23 10:36 UTC, mrjvs commented on src/components/SearchBar.tsx
> -        </DropdownButton>
nvm

2023-07-23 10:38 UTC, mrjvs approved these changes
Couldn't wait to work on my stuff today, so I decided to address the requested changes myself

2023-07-23 10:39 UTC, merged

2023-07-23 10:39 UTC, castdrian commented
haha alrighty-o excitement is fun