Improved Chromecast integration
movie-web/movie-web pull request #419
Opened 2023-08-31 16:49 UTC by FelixBoehme

This pull request resolves in parts #335.

 - [x] I have read and agreed to the [code of conduct](https://github.com/movie-web/movie-web/blob/dev/.github/CODE_OF_CONDUCT.md).
 - [x] I have read and complied with the [contributing guidelines](https://github.com/movie-web/movie-web/blob/dev/.github/CONTRIBUTING.md).
 - [x] I have tested all of my changes.

2023-08-31 17:03 UTC, castdrian requested changes

2023-08-31 17:03 UTC, castdrian commented on src/video/components/actions/CaptionRendererAction.tsx
> +  const casting = getPlayerState(descriptor).casting.isCasting;
```suggestion
  const { casting: { isCasting } } = getPlayerState(descriptor);
```

2023-08-31 17:03 UTC, castdrian commented on src/video/components/actions/ProgressAction.tsx
> +  const casting = getPlayerState(descriptor).casting.isCasting;
```suggestion
  const { casting: { isCasting } } = getPlayerState(descriptor);
```

2023-08-31 17:03 UTC, castdrian commented on src/video/components/actions/ProgressAction.tsx
> +      {isThumbnailVisible && !casting ? (
```suggestion
      {isThumbnailVisible && !isCasting ? (
```

2023-08-31 17:03 UTC, castdrian commented on src/video/components/actions/CaptionRendererAction.tsx
> +  if (casting) return null;
```suggestion
  if (isCasting) return null;
```

2023-08-31 17:04 UTC, mrjvs commented on src/video/components/actions/ProgressAction.tsx
> +  const casting = getPlayerState(descriptor).casting.isCasting;
I dont agree

2023-08-31 17:04 UTC, mrjvs commented on src/video/components/actions/ProgressAction.tsx
> +  const casting = getPlayerState(descriptor).casting.isCasting;
rename to isCasting is fine, no destructuring

2023-08-31 17:11 UTC, mrjvs commented on src/video/state/providers/castingStateProvider.ts
> +        subtitles.language = "en";
not all of our captions we support are vtt. we use a library to parse various formats to VTT.
do you know if its possible to load a data url (`data:text/vtt;base64,...`) or something similar?

2023-08-31 17:39 UTC, FelixBoehme commented on src/video/state/providers/castingStateProvider.ts
> +        subtitles.language = "en";
I'm not sure but I just realized when testing again, that this can't work. When testing I hosted it locally and used a fixed url for the subtitles to be able to test it, but i just realized, that it can't work in the way I imagined because the chromecast api has to have a url which can be loaded from the chromecast device which of course isn't possible with the blob approached used.
So sadly this won't work in the current state.
Don't know if I'll be able to come up with a fix for this, because simply using the the fetched urls won't always work if they're not in VTT format.
Sorry to disappoint, guess this feature will have to wait a bit longer.

2023-08-31 17:41 UTC, mrjvs commented on src/video/state/providers/castingStateProvider.ts
> +        subtitles.language = "en";
the data url might work, you could give it a shot.

2023-08-31 18:42 UTC, FelixBoehme commented on src/video/state/providers/castingStateProvider.ts
> +        subtitles.language = "en";
you mean the url before it is being parsed?

2023-08-31 21:47 UTC, FelixBoehme commented
I update it to use the url of the caption source, unfortunately the chromecast api seems to only support VTT and no other format.
So if the caption source is in the VTT format it does work, but otherwise not and it seems to be impossible to make it work unless the generated VTT file by you is hosted which I suspect you wouldn't want to do.
Hopefully if more subtitle providers are added this will hardly be an issue.

2023-09-01 12:57 UTC, mrjvs commented
even if the PR isn't fully featured, neither is the entire v4 branch.
so ill approve this if no major bugs come up in testing.

@binaryoverload, could you be a lad and test if casting still works as intended? (dont have a chromecast myself)

2023-09-02 11:37 UTC, JamesHawkinss commented
I've just tested this on my Chromecast-enabled device. Running into some issues:

* Subtitles only work on some movies, which is fine
* The Wolf of Wall Street seems to crash when scrubbing on the Chromecast device

No other major issues, I'm probably happy to merge

2023-09-02 13:46 UTC, binaryoverload approved these changes

2023-09-02 13:47 UTC, binaryoverload commented
@FelixBoehme please resolve the merge conflicts then I will be happy to merge this :)

2023-09-02 14:17 UTC, FelixBoehme commented
Im sorry I don't really know what to do this is my first PR and I have never resolved any conflicts how do I do this?
The button resolve conflicts is greyed out so I'm a little clueless on what to do now.

2023-09-02 14:18 UTC, binaryoverload commented
The best way is to merge the v4 branch into your branch locally, which will give you the merge issues to resolve. Then when those are resolved you can push again

2023-09-02 14:21 UTC, castdrian commented
merging branches isn't very clean though, ideally you always rebase instead

2023-09-02 14:25 UTC, FelixBoehme commented
good to know thanks, it should be resolved now I think

2023-09-02 14:41 UTC, FelixBoehme commented
Even though building the project failed I think I have fixed everything on my end but not sure. Hope this looks good now, let me know if there's anything I have missed and still need to fix

2023-09-02 14:50 UTC, binaryoverload commented
Not sure why it's not building, looks all good to me. Thanks again for the contribution @FelixBoehme

2023-09-02 14:50 UTC, merged