Upgrade packages, bundling, performance
movie-web/movie-web pull request #578
Opened 2023-12-23 05:26 UTC by rafcontreras

This pull request upgrades packages to latest versions, implements better bundling, improves performance

 - [x] I have read and agreed to the [code of conduct](https://github.com/movie-web/movie-web/blob/dev/.github/CODE_OF_CONDUCT.md).
 - [x] I have read and complied with the [contributing guidelines](https://github.com/movie-web/movie-web/blob/dev/.github/CONTRIBUTING.md).
 - [ ] What I'm implementing was assigned to me and is an [approved issue](https://github.com/movie-web/movie-web/issues?q=is%3Aopen+is%3Aissue+label%3Aapproved). For reference, please take a look at our [GitHub projects](https://github.com/movie-web/movie-web/projects).
 - [x] I have tested all of my changes.

2023-12-23 12:52 UTC, mrjvs requested changes
I agree with the premise of the PR but please communicate with us beforehand, we have an "approved" issue system for a reason. We want people to communicate these kinds of changes before acting on them.

2023-12-23 12:52 UTC, mrjvs commented on src/index.tsx
> +  <ErrorBoundary>
React.StrictMode was removed here. Is there a reason why? perhaps im missing some context.

2023-12-23 12:52 UTC, mrjvs commented on src/pages/parts/auth/TrustBackendPart.tsx
> +        </span>
Isn't this a breaking change for localization files?

The texts look like `Do you trust <0>{hostname}</0> for your backend?`. Doing it this way will make the `<0>` not work.

2023-12-23 12:52 UTC, mrjvs commented on src/pages/parts/player/MetaPart.tsx
> +      data = decodeTMDBId(params.media as string);
Why was this needed?

2023-12-23 12:52 UTC, mrjvs commented on src/setup/App.tsx
> +        />
Why were these pulled into two routes instead of one? They have identical contents.

2023-12-23 12:52 UTC, mrjvs commented on src/setup/App.tsx
> +        />
Same question for /browse and /. (right below)

2023-12-23 12:52 UTC, mrjvs commented on src/setup/App.tsx
> +          <Route path="/dmca" element={<DmcaPage />} />
Are the exact props no longer needed? is it default?

2023-12-23 12:52 UTC, mrjvs commented on vite.config.mts
> +      million.vite({ auto: true }),
While building, I'm getting a lot of million source map warnings. Is there a way to fix that?

2023-12-23 19:04 UTC, rafcontreras commented on src/index.tsx
> +  <ErrorBoundary>
While on Dev it gives console errors on some libraries, will re-add it again.

2023-12-23 19:05 UTC, rafcontreras commented on src/pages/parts/auth/TrustBackendPart.tsx
> +        </span>
Will fix that.

2023-12-23 19:06 UTC, rafcontreras commented on src/pages/parts/player/MetaPart.tsx
> +      data = decodeTMDBId(params.media as string);
I was getting linting errors as params.media could be `string | null` and it is expecting string.

2023-12-23 19:07 UTC, rafcontreras commented on src/setup/App.tsx
> +        />
Routes no longer accept arrays of paths, so I had to break them up into separate routes.

2023-12-23 19:08 UTC, rafcontreras commented on src/setup/App.tsx
> +          <Route path="/dmca" element={<DmcaPage />} />
That's right, in the documentation it says:

> You don't need to use an exact prop on <Route path="/"> anymore. This is because all paths match exactly by default. If you want to match more of the URL because you have child routes use a trailing * as in <Route path="users/*">.

2023-12-23 19:09 UTC, rafcontreras commented on vite.config.mts
> +      million.vite({ auto: true }),
They are only warnings, while opening source maps in the browser all seems ok.

2023-12-23 19:26 UTC, mrjvs commented on vite.config.mts
> +      million.vite({ auto: true }),
It does seem like the output is fine, I've mentioned this case in an existing bug report: https://github.com/aidenybai/million/issues/844

We can keep it like this for now, when it's hopefully fixed in the next version of million, we can just update.

2023-12-23 19:26 UTC, mrjvs commented on src/setup/App.tsx
> +          <Route path="/dmca" element={<DmcaPage />} />
Oh cool, good change on their end.

2023-12-23 19:27 UTC, mrjvs commented on src/pages/parts/player/MetaPart.tsx
> +      data = decodeTMDBId(params.media as string);
It seems they changed the type of useParams then.
Instead of casting, I'd rather have a explicit check for it that just throws if media param isn't set. (inside the useAsync)

2023-12-23 19:28 UTC, mrjvs commented on src/setup/App.tsx
> +        />
Hmm, annoying change. but code should be good then. We can keep it like this.

2023-12-24 01:58 UTC, rafcontreras commented on src/index.tsx
> +  <ErrorBoundary>
Re-added StrictMode

2023-12-24 01:59 UTC, rafcontreras commented on src/pages/parts/auth/TrustBackendPart.tsx
> +        </span>
I've modified the code.

2023-12-24 02:00 UTC, rafcontreras commented on src/pages/parts/player/MetaPart.tsx
> +      data = decodeTMDBId(params.media as string);
Now it throws an error if the param isn't set

2023-12-24 13:06 UTC, mrjvs commented on src/pages/parts/auth/TrustBackendPart.tsx
> +        </span>
Seems like it's still not resolved.
The only white part should be the hostname, perhaps you can just revert it to what it was orginally?
![https://i.imgur.com/IuYY0fc.png](https://i.imgur.com/IuYY0fc.png)

2023-12-24 13:25 UTC, mrjvs commented on src/pages/parts/auth/TrustBackendPart.tsx
> +        </span>
Decided to fix it myself, cuz I wanted to play around with some of the bundling myself anyway.
Fixed in latest commit

2023-12-24 13:25 UTC, mrjvs approved these changes

2023-12-24 13:25 UTC, merged

2023-12-24 13:26 UTC, mrjvs commented
Thanks for your PR, im sure our users will appreciate the optimizations :)