Improve video progress/playback keybinds
movie-web/movie-web pull request #612
Opened 2023-12-28 20:09 UTC by qtchaos

This pull request resolves #577 and #573.

Implemented *most* of the [YouTube player shortcuts](https://support.google.com/youtube/answer/7631406), the only outliers being the `,` and `.` keys which skip backward and forward by a frame respectively, since I don't believe we can skip the video with that much granularity I decided these should instead use 1 second.

Adds the following shortcuts in the player:
 * `0` Seek to the beginning of the media.
 * `1-9` Seek to the 10% to 90% of the media.
 * `J` Seek backward 10 seconds in player.
 * `l` Seek forward 10 seconds in player.
 * `,` While the video is paused, skip forward 1 second.
 * `.` While the video is paused, skip backward 1 second.
 * `<` Decrease playback speed
 * `>` Increase playback speed

 - [X] I have read and agreed to the [code of conduct](https://github.com/movie-web/movie-web/blob/dev/.github/CODE_OF_CONDUCT.md).
 - [X] I have read and complied with the [contributing guidelines](https://github.com/movie-web/movie-web/blob/dev/.github/CONTRIBUTING.md).
 - [X] What I'm implementing was assigned to me and is an [approved issue](https://github.com/movie-web/movie-web/issues?q=is%3Aopen+is%3Aissue+label%3Aapproved). For reference, please take a look at our [GitHub projects](https://github.com/movie-web/movie-web/projects).
 - [X] I have tested all of my changes.

2023-12-28 20:18 UTC, binaryoverload commented
Hi,

Thanks for doing this. As mentioned on the now closed #577, could you please remove the 0-9 skipping shortcuts as they make it too easy to lose your progress

2023-12-28 20:18 UTC, binaryoverload commented
Hi,

Thanks for doing this. As mentioned on the now closed #577, could you please remove the 0-9 skipping shortcuts as they make it too easy to lose your progress

2023-12-28 20:22 UTC, qtchaos commented
Removed seeking numbers in https://github.com/movie-web/movie-web/pull/612/commits/27b28a6d96b4742182f4cb96841e6b52c1110712 👍

2023-12-28 20:32 UTC, binaryoverload requested changes

2023-12-28 20:32 UTC, binaryoverload commented on src/components/player/internals/KeyboardEvents.tsx
> +        const nextIdx = idx + (k === ">" ? 1 : -1);
If the existing index doesn't exist (Which may be possible if we change the settings implementation in the future) then we should handle that

I suggest defaulting the index to the index of `1` (2 in this case) if the index is -1

2023-12-28 20:32 UTC, binaryoverload commented on src/components/player/internals/KeyboardEvents.tsx
> +      if (k === "." && dataRef.current.mediaPlaying?.isPaused)
It might be a good idea to pause when you press the keybind (I believe this is the behaviour of YouTube). Thoughts?

2023-12-28 20:46 UTC, qtchaos commented on src/components/player/internals/KeyboardEvents.tsx
> +      if (k === "." && dataRef.current.mediaPlaying?.isPaused)
YouTube doesn't pause the video when using the `j` or `l` shortcuts, If we would pause the video when using them. it would probably reduce playback lag when pressed multiple times in a row. If you think that might be better then I'll implement those changes, but I really have no direct opinion.

2023-12-28 20:48 UTC, binaryoverload commented on src/components/player/internals/KeyboardEvents.tsx
> +      if (k === "." && dataRef.current.mediaPlaying?.isPaused)
Oh I see it only works on YT when paused - that's fine then

2023-12-28 20:54 UTC, qtchaos commented on src/components/player/internals/KeyboardEvents.tsx
> +        const nextIdx = idx + (k === ">" ? 1 : -1);
Added these changes in https://github.com/movie-web/movie-web/pull/612/commits/5e52ea8e8fdcea482be57b75ee94c46c00c5e33d

2023-12-29 05:16 UTC, zisra commented
Keybinds should somehow be documented, maybe through the discord bot, FAQ page, or docs

2023-12-29 12:22 UTC, merged