Migrate libraries: ISO-639-1 -> locale-code
movie-web/movie-web pull request #619
Opened 2023-12-29 11:52 UTC by GustavoMelloGit

This pull request resolves the issue where the ISO-639-1 library has a very limited number of languages, excluding variants such as pt-BR.

 - [x] I have read and agreed to the [code of conduct](https://github.com/movie-web/movie-web/blob/dev/.github/CODE_OF_CONDUCT.md).
 - [x] I have read and complied with the [contributing guidelines](https://github.com/movie-web/movie-web/blob/dev/.github/CONTRIBUTING.md).
 - [x] What I'm implementing was assigned to me and is an [approved issue](https://github.com/movie-web/movie-web/issues?q=is%3Aopen+is%3Aissue+label%3Aapproved). For reference, please take a look at our [GitHub projects](https://github.com/movie-web/movie-web/projects).
 - [x] I have tested all of my changes.

2023-12-29 12:28 UTC, mrjvs requested changes

2023-12-29 12:28 UTC, mrjvs commented on src/assets/locales/pt-BR.json
Please do not modify the translations manually, use the community translation tool. Check out contributing guidelines for more info.

2023-12-29 12:28 UTC, mrjvs commented on src/assets/languages.ts
> +export const rtlLocales: Locales[] = ["he-IL", "ar-SA"];
This is breaking change. People that already have a selected language selected will be changed back to english. Plus the preferred language stored on the account would be wrong.

If we're going to support alpha-2 iso codes. It will need to be backwards compatible.

Not to mention that subtitles from provider package will still be using the other codes, so subtitles will likely break as well then.

2023-12-29 23:06 UTC, GustavoMelloGit commented on src/assets/languages.ts
> +export const rtlLocales: Locales[] = ["he-IL", "ar-SA"];
> Not to mention that subtitles from provider package will still be using the other codes, so subtitles will likely break as well then.

What do you propose to fix that? I have no idea what to do...

2024-01-01 23:42 UTC, binaryoverload commented
Due to the complexities of implementing this feature, we have decided that the core team will do it ourselves. Apologies for wasting your time - thank you for your effort!

2024-01-01 23:42 UTC, closed without merging