fix: movies with unavailable posters will be shown in the last row
movie-web/movie-web pull request #673
Opened 2023-12-30 17:14 UTC by ashudevcodes

This pull request resolves #665 

 - [x] I have read and agreed to the [code of conduct](https://github.com/movie-web/movie-web/blob/dev/.github/CODE_OF_CONDUCT.md).
 - [x] I have read and complied with the [contributing guidelines](https://github.com/movie-web/movie-web/blob/dev/.github/CONTRIBUTING.md).
 - [x] What I'm implementing was assigned to me and is an [approved issue](https://github.com/movie-web/movie-web/issues?q=is%3Aopen+is%3Aissue+label%3Aapproved). For reference, please take a look at our [GitHub projects](https://github.com/movie-web/movie-web/projects).
 - [x] I have tested all of my changes.

# All movies with unavailable posters will be shown in the last row
![image](https://github.com/movie-web/movie-web/assets/105356967/3dad8b68-3c2d-4894-a0d8-5f2b447e2f5a)
![image](https://github.com/movie-web/movie-web/assets/105356967/aaf16027-92af-47b0-a85f-97ee459c10bf)

2023-12-30 17:27 UTC, qtchaos commented on src/backend/metadata/search.ts
> +
pnpm lint:fix

2024-01-01 16:10 UTC, mrjvs requested changes

2024-01-01 16:10 UTC, mrjvs commented on src/backend/metadata/search.ts
> +    return 0;
This destroys the order that the undefined posts come in.
Especially since the sequence of when the elements get compared is undefined behaviour, so sorting would come out randomized in theory.

This fix probably can't be done with a sort(), so I recommend making two seperate arrays (with poster and without poster) using filter(). then concatinating them.

2024-01-01 16:13 UTC, binaryoverload commented on src/backend/metadata/search.ts
> +    return 0;
Sorting shouldn't come out as randomised since Array.sort is a stable sort surely?

2024-01-01 16:23 UTC, binaryoverload commented on src/backend/metadata/search.ts
> +    return 0;
After a discussion internally, please proceed with JVS's suggestion of filtering @ashudevcodes

2024-01-02 10:11 UTC, binaryoverload requested changes

2024-01-02 10:11 UTC, binaryoverload commented on src/backend/metadata/search.ts
> +  const sortedresult = movieWithposters.concat(movieWithoutposters);
Minor stylistic nit-pick

```suggestion
  const movieWithPosters = results.filter((movie) => movie.poster);
  const movieWithoutPosters = results.filter((movie) => !movie.poster);

  const sortedresult = movieWithPosters.concat(movieWithoutPosters);
```

2024-01-02 18:53 UTC, mrjvs approved these changes

2024-01-02 18:54 UTC, merged