Implement MediaSession support
movie-web/movie-web pull request #721
Opened 2024-01-05 19:29 UTC by qtchaos

This pull request resolves #176

Adds all video related MediaSession functionality.

Tried to limit updating media progress as much as possible, not sure if this is necessary or not, but thought it would be nice. This unfortunately complicates the code a bit, so if this isn't necessary I'll remove it.

Not that happy with the structure of the MediaSession component, i guess I'll see what reviews think :)

 - [X] I have read and agreed to the [code of conduct](https://github.com/movie-web/movie-web/blob/dev/.github/CODE_OF_CONDUCT.md).
 - [X] I have read and complied with the [contributing guidelines](https://github.com/movie-web/movie-web/blob/dev/.github/CONTRIBUTING.md).
 - [X] What I'm implementing was assigned to me and is an [approved issue](https://github.com/movie-web/movie-web/issues?q=is%3Aopen+is%3Aissue+label%3Aapproved). For reference, please take a look at our [GitHub projects](https://github.com/movie-web/movie-web/projects).
 - [X] I have tested all of my changes.

2024-01-06 14:28 UTC, mrjvs requested changes
On top of the few bugs I found. There also seems to be a lack of event listening on the clients end. For example, how does the mediasession state get updated if the user pauses on our player? Using useEffect, you should be able to listen to changes to our state and update the mediasession accordingly.

2024-01-06 14:28 UTC, mrjvs commented on src/components/player/internals/MediaSession.ts
> +    }
for movies, this will also show the previoustrack button. since episode is null and `null !== 1` evaluates true

2024-01-06 14:28 UTC, mrjvs commented on src/components/player/internals/MediaSession.ts
> +    });
seems like if you both the seek forward/backward and seekto. the progress bar doesn't show. So maybe only implement seekto https://stackoverflow.com/a/76090643

2024-01-31 16:10 UTC, mrjvs commented
Play pause seems to work nicely, but next/prev buttons seem to not update the state properly.
It goes to the next episode, but your components thinks its still the old one. So next episode again won't trigger it correctly. Also the url doesn't update when switching episode. See gif for reproduction:

[!https://i.imgur.com/6y4N2dW.gif](https://i.imgur.com/6y4N2dW.gif)

2024-03-07 15:52 UTC, binaryoverload approved these changes

2024-03-07 15:54 UTC, merged

2024-03-07 15:58 UTC, mrjvs commented
Holy shit, it got merged :tada: