Push Docker image to registry after release
movie-web/movie-web pull request #722
Opened 2024-01-05 22:24 UTC by sweenu

This pull request resolves #675

 - [ ] I have read and agreed to the [code of conduct](https://github.com/movie-web/movie-web/blob/dev/.github/CODE_OF_CONDUCT.md).
 - [ ] I have read and complied with the [contributing guidelines](https://github.com/movie-web/movie-web/blob/dev/.github/CONTRIBUTING.md).
 - [x] What I'm implementing was assigned to me and is an [approved issue](https://github.com/movie-web/movie-web/issues?q=is%3Aopen+is%3Aissue+label%3Aapproved). For reference, please take a look at our [GitHub projects](https://github.com/movie-web/movie-web/projects).
 - [x] I have tested all of my changes.

2024-01-05 22:27 UTC, mrjvs commented
@weeryan17

2024-01-05 22:28 UTC, sweenu commented
I'd like to change the CMD to an ENTRYPOINT to a script that will change the config file from the environment variables and then run nginx, but I wanted to know first if there was a way for the application to be able to read from environment variables directly the way it does it when we deploy with Vercel. That would be way cleaner.

2024-01-05 22:43 UTC, binaryoverload requested changes

2024-01-05 22:43 UTC, binaryoverload commented on dockerfile
> +RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install
I think we should keep this, as this is a CI specific flag that won't be enabled by default as we're not running it in the GH Action directly

2024-01-06 09:54 UTC, binaryoverload approved these changes

2024-01-06 10:44 UTC, merged