fixed #614 multiple captions of the same language all appeared as selected when selecting only one
movie-web/movie-web pull request #725
Opened 2024-01-06 08:15 UTC by CelestialLemon

This pull request resolves #614

 - [x] I have read and agreed to the [code of conduct](https://github.com/movie-web/movie-web/blob/dev/.github/CODE_OF_CONDUCT.md).
 - [x] I have read and complied with the [contributing guidelines](https://github.com/movie-web/movie-web/blob/dev/.github/CONTRIBUTING.md).
 - [x] What I'm implementing was assigned to me and is an [approved issue](https://github.com/movie-web/movie-web/issues?q=is%3Aopen+is%3Aissue+label%3Aapproved). For reference, please take a look at our [GitHub projects](https://github.com/movie-web/movie-web/projects).
 - [x] I have tested all of my changes.

IDs for the captions were added to the providers package recently. Now instead of using language to set the selected caption we can use the ID of that captions. This fixes the issue where we have multiple subtitles of the same language which all appeared selected when selecting only one of them. 

It's my first PR to this project and I'm new here so let me know if anything else is required to be done here. Thanks.

2024-01-06 13:47 UTC, mrjvs requested changes
Look good overal, just two small bits of cleanup and then it should be good to go.

2024-01-06 13:47 UTC, mrjvs commented on src/components/player/atoms/settings/CaptionsView.tsx
>          key={`${i}-${v.url}`}
I think this key can also be with the id. no longer needs the eslint disable comment too

2024-01-06 13:47 UTC, mrjvs commented on src/components/player/hooks/useCaptions.ts
>          url: caption.url,
This method should call the new `selectCaptionById` after its found the correct caption.

2024-01-06 17:50 UTC, CelestialLemon commented
Changes done.

2024-01-09 05:13 UTC, CelestialLemon commented
Done.

2024-01-11 18:02 UTC, mrjvs approved these changes

2024-01-11 20:20 UTC, merged