Created an 'x' button to clear search query
movie-web/movie-web pull request #825
Opened 2024-01-25 02:47 UTC by RyloRiz

This pull request resolves #824

 - [x] I have read and agreed to the [code of 
conduct](https://github.com/movie-web/movie-web/blob/dev/.github/CODE_OF_CONDUCT.md).
 - [x] I have read and complied with the [contributing 
guidelines](https://github.com/movie-web/movie-web/blob/dev/.github/CONTRIBUTING.md).
 - [ ] What I'm implementing was assigned to me and is an [approved issue](https://github.com/movie-web/movie-web/issues?q=is%3Aopen+is%3Aissue+label%3Aapproved). For reference, please take a look at our [GitHub projects](https://github.com/movie-web/movie-web/projects).
 - [x] I have tested all of my changes.

2024-01-25 20:08 UTC, mrjvs requested changes

2024-01-25 20:08 UTC, mrjvs commented on src/components/form/SearchBar.tsx
> +            className="cursor-pointer absolute bottom-0 right-5 top-0 flex max-h-14 items-center text-search-icon"
Few things regarding the look and feel of the button:
1. It needs a hover effect and an mousedown effect (active). lets do:
    - Show a circular background on hover, make the icon white
    - When holding down mouse click, add a `scale-110`.
2. Hitbox is currently super thin but stretched from top to bottom. make the hitbox this instead:
![https://i.imgur.com/a832qg3.png](https://i.imgur.com/a832qg3.png)

2024-01-25 20:08 UTC, mrjvs commented on src/components/form/SearchBar.tsx
> +              setSearch("");
Because this unfocuses first, then resets the search input (on desktop with mouse), it will not update the URL after clearing. Fix it by triggering the onfocus event manually after clearing.

2024-01-25 20:08 UTC, mrjvs commented on src/components/form/SearchBar.tsx
> +          <div
Let's make this only show if something is actually typed into the field, it's weird to have an clear button when you haven't done anything yet.

2024-01-28 05:42 UTC, RyloRiz commented
@mrjvs All requests have been implemented & tested on both desktop and mobile, please let me know if there are any issues.

2024-01-28 20:15 UTC, mrjvs requested changes
I appreciate the effort, but this is kinda overcomplicated.
Here are ways to make it simpler, that'd id like to see in this PR:

For the hiding of the clearbutton, use conditional rendering: https://react.dev/learn/conditional-rendering
The condition can just be `props.value.length > 0`.

For the url fixes, all you needed to do is set this as onclick handler:
```ts
onClick={() => {
  setSearch("");
  props.onFocus();
}}
```

For the hover effects, you can just put the text colors on the clickable hitbox of the div. no need to use groups to dig it down further. The icon inherits the text color from it's parents.

With those approaches, you wont need useEffect, useRef or need to add another state variable.

2024-01-28 20:15 UTC, mrjvs commented on themes/default.ts
> +        hoverBackground: tokens.shade.c600,
Make sure to add this to all color themes, not just default. It will be just a copy paste into those other files, so not a lot of effort.

2024-01-28 21:50 UTC, RyloRiz commented
> For the url fixes, all you needed to do is set this as onclick handler:

As `setSearch/setState` is an asynchronous process, the `search` variable does not update in time for `props.onUnFocus` to properly update the URL. The current system using these two lines as the clear button's `onClick` works as follows:

```ts
setSearch("");
props.onUnFocus();
```

*Assume the current search term is **"test"***:

* `TextInputControl`'s `onBlur` handler fires `onUnFocus`, which sets the URL to the current (old) query (the textinputcontrol was unfocused in favor of the clear button)
* `setSearch` fires with **no** URL-updating permission (`commitToUrl = false`) and the intent to update the query to `""`
* `props.onUnFocus` fires immediately after **with** URL-updating permission (`commitToUrl = true`), *but* `search` has not updated yet due to the asynchronous nature of `setSearch/setState` and instead this re-applies the old query as the new query

A possible fix is to edit the `onUnFocus` function declaration in the `useSearchQuery` hook to allow for an optional parameter that would use it instead of the current value of `search` and pass that along to the `updateParams` call that *does* have the permission to update the URL. I can confirm through testing that this method does work as intended.

All other concerns outlined in your reply have been fixed without issues.

2024-01-29 17:54 UTC, mrjvs commented
> A possible fix is to edit the `onUnFocus` function declaration in the `useSearchQuery` hook to allow for an optional parameter that would use it instead of the current value of `search` and pass that along to the `updateParams` call that _does_ have the permission to update the URL. I can confirm through testing that this method does work as intended.

I like this method, let's go with that!

2024-01-30 19:40 UTC, mrjvs approved these changes

2024-01-30 19:50 UTC, merged