Patch 2
movie-web/movie-web pull request #860
Opened 2024-01-31 21:24 UTC by ari-party

This pull request resolves #857 

 - [x] I have read and agreed to the [code of conduct](https://github.com/movie-web/movie-web/blob/dev/.github/CODE_OF_CONDUCT.md).
 - [x] I have read and complied with the [contributing guidelines](https://github.com/movie-web/movie-web/blob/dev/.github/CONTRIBUTING.md).
 - [x] What I'm implementing was assigned to me and is an [approved issue](https://github.com/movie-web/movie-web/issues?q=is%3Aopen+is%3Aissue+label%3Aapproved). For reference, please take a look at our [GitHub projects](https://github.com/movie-web/movie-web/projects).
 - [x] I have tested all of my changes.

![image](https://github.com/movie-web/movie-web/assets/49074962/b2912ded-c3a1-40ed-9e50-e5b69fed1b86)
Allows left click and context menu > copy link address to copy.

2024-01-31 21:30 UTC, zisra commented
Using this would be more consistent with the rest of the codebase
```js
import { useCopyToClipboard } from "react-use";
```

2024-02-03 21:02 UTC, mrjvs requested changes

2024-02-03 21:02 UTC, mrjvs commented on src/assets/locales/en.json
> +        "downloadPlaylist": "Copy playlist link",
You should change key from "downloadPlaylist" to "copyHlsPlaylist" and make the text "Copy HLS playlist link".
This is so the translations that currently exist for this key will fallback to english and not the old text.

2024-02-03 21:13 UTC, mrjvs commented
It seems you've missed the other request I had in the comment. There were two things addressed.

2024-02-03 21:31 UTC, mrjvs approved these changes

2024-02-03 21:32 UTC, merged