Add dynamic and engaging search bar placeholders
movie-web/movie-web pull request #920
Opened 2024-02-17 18:02 UTC by vijaysingh2219

Enhance search bar experience with 5 dynamic placeholders for the movie web app. Provides a mix of engaging questions and suggestions, promoting user interaction and a personalized feel. Shuffled for a random appearance, contributing to a more dynamic user experience.

This pull request resolves #918 

 - [x] I have read and agreed to the [code of conduct](https://github.com/movie-web/movie-web/blob/dev/.github/CODE_OF_CONDUCT.md).
 - [x] I have read and complied with the [contributing guidelines](https://github.com/movie-web/movie-web/blob/dev/.github/CONTRIBUTING.md).
 - [x] What I'm implementing was assigned to me and is an [approved issue](https://github.com/movie-web/movie-web/issues?q=is%3Aopen+is%3Aissue+label%3Aapproved). For reference, please take a look at our [GitHub projects](https://github.com/movie-web/movie-web/projects).
 - [x] I have tested all of my changes.

2024-02-17 18:15 UTC, JipFr commented on src/assets/locales/en.json
> +          "What's your cinematic preference today?",
Am I crazy if I feel like this is just weird?

2024-02-17 18:19 UTC, TheScreechingBagel commented on src/assets/locales/en.json
> +          "What's your cinematic preference today?",
crazy? i was crazy once. they

2024-02-17 23:45 UTC, binaryoverload requested changes

2024-02-17 23:45 UTC, binaryoverload commented on src/assets/locales/en.json
> +      "placeholder": {
I feel like this may cause an issue, as I don't know how Weblate will handle the change in type from string -> object

I think the best solution is to change the name of the key completely

2024-02-18 10:00 UTC, castdrian commented on src/assets/locales/en.json
> +      "placeholder": {
what is it with the chatgpt responses

2024-02-19 14:59 UTC, adlazaro commented
Hey @vijaysingh2219, I really like the idea behind #918, but I feel like some of the current placeholder options might be too lengthy and verbose. The text could override the search bar on mobile devices:

![movie-web-placeholder-long](https://github.com/movie-web/movie-web/assets/72154755/59355c35-ae4b-47e7-85c1-2fdeee7987f4)

2024-02-20 09:43 UTC, binaryoverload requested changes
Mostly looks good, please just reduce the number of randomised English options to 5 - the current number is too many and will just mean the translators have the translate loads

2024-02-20 09:45 UTC, binaryoverload commented
In removing the excess from the list, please make sure to use the shorter ones so we don't run into the issue that @adlazaro talked about

2024-02-20 10:39 UTC, binaryoverload requested changes
Thanks for the changes, please now fix the ESLint error on line 29 in `HeroPart.tsx`

2024-02-20 11:10 UTC, binaryoverload approved these changes

2024-02-20 11:10 UTC, binaryoverload commented
Looks good to me, I am going to ask @mrjvs to check I haven't missed anything

2024-02-21 18:11 UTC, merged