Add appearance preview
movie-web/movie-web pull request #922
Opened 2024-02-18 20:04 UTC by marcoslor

This pull request resolves #868 

 - [x] I have read and agreed to the [code of conduct](https://github.com/movie-web/movie-web/blob/dev/.github/CODE_OF_CONDUCT.md).
 - [x] I have read and complied with the [contributing guidelines](https://github.com/movie-web/movie-web/blob/dev/.github/CONTRIBUTING.md).
 - [x] What I'm implementing was assigned to me and is an [approved issue](https://github.com/movie-web/movie-web/issues?q=is%3Aopen+is%3Aissue+label%3Aapproved). For reference, please take a look at our [GitHub projects](https://github.com/movie-web/movie-web/projects).
 - [x] I have tested all of my changes.

## Changelog
- The user previews the chosen theme right after selecting it.
- The theme option checkmark and border hints which theme is under preview.
- The "Active" badge right over the theme option hints which theme is in use.
- The theme preview state is cleared out when the user leaves the settings page, or discards their changes.
- A little transition happens to the page background when a different theme is selected.

## Preview

![image](https://github.com/movie-web/movie-web/assets/37618554/9ebefefd-524e-441d-934c-aae82362a084)
<video width="630" height="300" src="https://github.com/movie-web/movie-web/assets/37618554/964ace62-41a7-4a45-8ab4-6fc6c72ba301"></video>

2024-02-18 20:39 UTC, marcoslor commented
This was approved, but was not assigned to me. Another community member was also working on this.

I hope that is not an issue.

2024-02-18 21:41 UTC, DylanBT928 commented
Thank you for helping out on my issue!

2024-02-21 19:14 UTC, binaryoverload requested changes

2024-02-21 19:14 UTC, binaryoverload commented on src/pages/Settings.tsx
> +  activeThemeRef.current = activeTheme;
How come you've made a ref here instead of using the variable itself?

2024-02-26 21:13 UTC, merged