Remove references to official domain
movie-web/movie-web pull request #938
Opened 2024-02-23 14:28 UTC by qtchaos

This PR removes all links to the former official site and cancels all analytics related functions if backend is not set.

 - [X] I have read and agreed to the [code of conduct](https://github.com/movie-web/movie-web/blob/dev/.github/CODE_OF_CONDUCT.md).
 - [X] I have read and complied with the [contributing guidelines](https://github.com/movie-web/movie-web/blob/dev/.github/CONTRIBUTING.md).
 - [ ] What I'm implementing was assigned to me and is an [approved issue](https://github.com/movie-web/movie-web/issues?q=is%3Aopen+is%3Aissue+label%3Aapproved). For reference, please take a look at our [GitHub projects](https://github.com/movie-web/movie-web/projects).
 - [X] I have tested all of my changes.

2024-02-23 14:36 UTC, binaryoverload requested changes

2024-02-23 14:36 UTC, binaryoverload commented on src/backend/accounts/progress.ts
> +  if (!BACKEND_URL) return;
I think we should handle this higher up the chain because this doesn't account for users overriding the backend URL. In `ProgessSyncer.tsx` we call the `useBackendUrl` which could return undefined.

Could you modify the return type of `useBackendUrl` to return `string | undefined`, and then modify `ProgessSyncer.tsx` to return early if the URL is undefined

2024-02-25 22:19 UTC, binaryoverload approved these changes

2024-02-25 22:19 UTC, merged

2024-02-26 01:21 UTC, TheScreechingBagel commented on .github/CONTRIBUTING.md
>  1. First make sure you make an account. (click the link above)
there's no new "link above" yet btw

2024-02-26 01:51 UTC, qtchaos commented on .github/CONTRIBUTING.md
>  1. First make sure you make an account. (click the link above)
~~forgot about that one~~ just as planned... ill add it back once we get a pretty domain for weblate 😎