Extension: Prepare stream for all domains in a hls playlist
movie-web/movie-web pull request #947
Opened 2024-02-27 22:21 UTC by JorrinKievit

This pull request resolves #905 and VidSrcTo

There was also a bug in the hlsLevelQuality function, sometimes levels don't exist and it throws an error which causes the code after not to run.

 - [x] I have read and agreed to the [code of conduct](https://github.com/movie-web/movie-web/blob/dev/.github/CODE_OF_CONDUCT.md).
 - [x] I have read and complied with the [contributing guidelines](https://github.com/movie-web/movie-web/blob/dev/.github/CONTRIBUTING.md).
 - [x] What I'm implementing was assigned to me and is an [approved issue](https://github.com/movie-web/movie-web/issues?q=is%3Aopen+is%3Aissue+label%3Aapproved). For reference, please take a look at our [GitHub projects](https://github.com/movie-web/movie-web/projects).
 - [x] I have tested all of my changes.

2024-02-27 23:28 UTC, sudo-flix commented
looks fire

2024-02-28 11:33 UTC, binaryoverload requested changes

2024-02-28 11:33 UTC, binaryoverload commented on src/components/player/display/base.ts
> +                (v) => new URL(v.url).hostname,
Is there any chance of a URL being undefined/invalid format on a fragment - worth handling?

2024-02-28 12:17 UTC, JorrinKievit commented on src/components/player/display/base.ts
> +                (v) => new URL(v.url).hostname,
Good point, not sure if hls.js handles that. Will check when I get the time (or if someone else wants to 😉)

2024-02-28 14:32 UTC, qtchaos commented on src/components/player/display/base.ts
> +                (v) => new URL(v.url).hostname,
Would something like this be enough? If the URL is null we just use an empty string which will make the request 403 (black screen on player)

```ts
const chunkUrlsDomains = data.details.fragments.map(
  (v) => new URL(v.url).hostname ?? "",
);
```

2024-02-28 14:34 UTC, JorrinKievit commented on src/components/player/display/base.ts
> +                (v) => new URL(v.url).hostname,
Issue is more that new URL() can throw an error if the input is invalid

2024-02-28 14:49 UTC, qtchaos approved these changes

2024-02-28 14:58 UTC, merged